/**
 * AUTO-GENERATED by scripts/convert-sidebars.mjs from docs.json.
 * Locale: en
 * Each key on the default export corresponds to one Mintlify tab.
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  "ai-gateway": [
    {
      "type": "category",
      "label": "AI Gateway",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "ai-gateway/overview",
        "ai-gateway/llm-providers",
        "ai-gateway/token-quotas",
        "ai-gateway/cost-settings",
        "ai-gateway/reports",
        "ai-gateway/a2a-gateway",
        "ai-gateway/advanced-guardrails",
        "ai-gateway/multi-modal-endpoints",
        "ai-gateway/tracing-and-replay"
      ]
    }
  ],
  "overview": [
    {
      "type": "category",
      "label": "Getting Started",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "index"
      ]
    },
    {
      "type": "category",
      "label": "Understanding Apinizer",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "concepts/what-is-apinizer",
        "concepts/industry-benefits",
        "concepts/role-based-benefits",
        "concepts/technical-features",
        "concepts/architecture",
        {
          "type": "category",
          "label": "Deployment Topologies and Planning",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/deployment/overview",
            "concepts/deployment/software",
            "concepts/deployment/capacity-planning",
            "concepts/deployment/deployment-models",
            "concepts/deployment/topology-test-poc",
            "concepts/deployment/topology-professional",
            "concepts/deployment/topology-ha",
            "concepts/deployment/pre-installation-recommendations",
            "concepts/deployment/network-topology",
            "concepts/deployment/network-connection-matrix",
            "concepts/deployment/antivirus-configuration"
          ]
        },
        {
          "type": "category",
          "label": "Core Concepts and Terminology",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/core-concepts/what-is-environment",
            "concepts/core-concepts/what-is-project",
            "concepts/core-concepts/what-is-api-proxy",
            "concepts/core-concepts/what-is-policy",
            "concepts/core-concepts/error-message-configuration",
            "concepts/core-concepts/message-processing-and-policy-application",
            "concepts/core-concepts/content-encoding-and-compression",
            "concepts/core-concepts/conditional-policy-execution",
            "concepts/core-concepts/routing-and-upstream",
            "concepts/core-concepts/client-route",
            "concepts/core-concepts/connections",
            "concepts/core-concepts/connector",
            "concepts/core-concepts/endpoint",
            "concepts/core-concepts/variable",
            "concepts/core-concepts/dynamic-variables",
            "concepts/core-concepts/environment-variable",
            "concepts/core-concepts/api-proxy-group"
          ]
        },
        {
          "type": "category",
          "label": "Core Components",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/core-components/api-manager",
            "concepts/core-components/api-gateway",
            "concepts/core-components/identity-manager",
            "concepts/core-components/analytics-engine",
            "concepts/core-components/api-portal",
            "concepts/core-components/api-designer",
            "concepts/core-components/api-creator",
            "concepts/core-components/api-integrator",
            "concepts/core-components/cache-component",
            "concepts/core-components/monitoring-component"
          ]
        },
        {
          "type": "category",
          "label": "Supported Technologies",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/supported-technologies/supported-libraries",
            "concepts/supported-technologies/supported-protocols",
            "concepts/supported-technologies/supported-databases"
          ]
        },
        "concepts/glossary",
        "concepts/compliance-and-data-protection",
        "concepts/benchmark-results"
      ]
    }
  ],
  "versions": [
    "release-notes/overview",
    "release-notes/change-log",
    "release-notes/release-notes-2026",
    "release-notes/release-notes-2025",
    "release-notes/release-notes-2024",
    "release-notes/release-notes-2023",
    "release-notes/release-notes-2022",
    "release-notes/release-notes-2021",
    "release-notes/deprecated-and-removed",
    "release-notes/roadmap"
  ],
  "installation-and-update": [
    {
      "type": "category",
      "label": "Installation",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "setup/installations-overview",
        "setup/kubernetes",
        "setup/virtual-server",
        {
          "type": "category",
          "label": "Docker Installation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "setup/docker/overview",
            "setup/docker/all-in-one",
            "setup/docker/docker-compose",
            "setup/docker/apimanager",
            "setup/docker/apiworker",
            "setup/docker/apicache",
            "setup/docker/apiintegration",
            "setup/docker/apiportal"
          ]
        },
        {
          "type": "category",
          "label": "MongoDB Installation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "setup/mongodb/ubuntu-mongodb",
            "setup/mongodb/rhel-mongodb"
          ]
        },
        "setup/gateway-settings",
        "setup/uninstall",
        "setup/troubleshooting"
      ]
    },
    {
      "type": "category",
      "label": "Upgrade",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "upgrade/apinizer-version-upgrade",
        "upgrade/kubernetes-version-upgrade",
        "upgrade/mongodb-version-upgrade",
        "upgrade/elasticsearch-version-upgrade"
      ]
    },
    {
      "type": "category",
      "label": "Infrastructure Components Installation",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Kubernetes Cluster Preparation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/kubernetes/ubuntu-kubernetes",
            "installation/kubernetes/rhel-kubernetes",
            "installation/kubernetes/kubernetes-metric-server",
            "installation/kubernetes/kubernetes-high-availability-cluster",
            "installation/kubernetes/kubernetes-dashboard",
            "installation/kubernetes/prometheus-grafana",
            "installation/kubernetes/version-management-with-argocd"
          ]
        },
        {
          "type": "category",
          "label": "Elasticsearch (optional)",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/elasticsearch/ubuntu-elasticsearch",
            "installation/elasticsearch/ubuntu-elasticsearch-8.17.10",
            "installation/elasticsearch/rhel-elasticsearch",
            "installation/elasticsearch/rhel-elasticsearch-8.17.10",
            "installation/elasticsearch/simple-authentication",
            "installation/elasticsearch/permission-requirements",
            "installation/elasticsearch/backup-policy",
            "installation/elasticsearch/manual-ilm-policy-and-template-creation"
          ]
        },
        {
          "type": "category",
          "label": "Cloud Providers",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/cloud/amazon-eks-elastic-kubernetes-service",
            "installation/cloud/microsoft-aks-azure-kubernetes-service",
            "installation/cloud/openshift-origin-311"
          ]
        },
        {
          "type": "category",
          "label": "Offline Installation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/offline/introduction",
            "installation/offline/ubuntu",
            "installation/offline/rhel-8x",
            "installation/offline/rhel-9x"
          ]
        }
      ]
    }
  ],
  "managing-apis": [
    {
      "type": "category",
      "label": "API Development",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/quick-start",
        {
          "type": "category",
          "label": "API Design",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-design/spec-designer",
            "develop/api-design/data-models"
          ]
        },
        "develop/api-list-management",
        {
          "type": "category",
          "label": "API Proxy Creation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-proxy-creation/client-route-settings",
            "develop/api-proxy-creation/api-proxy-creation",
            "develop/api-proxy-creation/rest-api-proxy-creation",
            "develop/api-proxy-creation/soap-api-proxy-creation",
            "develop/api-proxy-creation/soap-rest-api-proxy-creation",
            "develop/api-proxy-creation/websocket-api-proxy-creation",
            "develop/api-proxy-creation/grpc-api-proxy-creation",
            "develop/api-proxy-creation/api-creator-db-api-creation",
            "develop/api-proxy-creation/api-creator-script-api-creation",
            "develop/api-proxy-creation/api-creator-mock-api-creation",
            "develop/api-proxy-creation/connector-api-proxy-creation",
            "develop/api-proxy-creation/multiple-schema-port-wsdl"
          ]
        },
        "develop/api-proxy-group-creation",
        {
          "type": "category",
          "label": "API Proxy Configuration",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-proxy-configuration/overview",
            "develop/api-proxy-configuration/settings",
            "develop/api-proxy-configuration/design",
            "develop/api-proxy-configuration/endpoint-configuration",
            "develop/api-proxy-configuration/client-route",
            "develop/api-proxy-configuration/soap-method-configuration",
            "develop/api-proxy-configuration/policy-management",
            "develop/api-proxy-configuration/api-traffic-log-settings",
            "develop/api-proxy-configuration/deployment-and-specification-information"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Routing",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/routing/http-routing",
        "develop/routing/grpc-routing",
        "develop/routing/websocket-routing",
        "develop/routing/retry-and-failover",
        "develop/routing/canary-and-traffic-mirroring",
        "develop/routing/sticky-session"
      ]
    },
    {
      "type": "category",
      "label": "Policies",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Authentication",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/plain-text-authentication",
            "develop/policies/digest-authentication",
            "develop/policies/message-flow-and-policy-management",
            "develop/policies/log",
            "develop/policies/basic-authentication",
            "develop/policies/jwt",
            "develop/policies/oauth2",
            "develop/policies/oidc-authentication",
            "develop/policies/mtls-authentication",
            "develop/policies/backend-api-authentication",
            "develop/policies/jose-verification",
            "develop/policies/jose-application-policy",
            "develop/policies/saml-authentication"
          ]
        },
        {
          "type": "category",
          "label": "Access Control",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/allowed-ip-list",
            "develop/policies/blocked-ip-list",
            "develop/policies/client-ban",
            "develop/policies/time-restriction",
            "develop/policies/api-based-throttling",
            "develop/policies/api-based-quota"
          ]
        },
        {
          "type": "category",
          "label": "Message Validation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/digital-signature",
            "develop/policies/digital-signature-verification",
            "develop/policies/encryption",
            "develop/policies/decryption",
            "develop/policies/json-schema-validation",
            "develop/policies/xml-schema-validation",
            "develop/policies/max-message-size",
            "develop/policies/min-message-size"
          ]
        },
        {
          "type": "category",
          "label": "Transformation and Processing",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/json-transformation",
            "develop/policies/xml-transformation",
            "develop/policies/script",
            "develop/policies/business-rule",
            "develop/policies/content-filter",
            "develop/policies/api-call",
            "develop/policies/cache",
            "develop/policies/redaction",
            "develop/policies/log-policy",
            "develop/policies/message-builder"
          ]
        },
        {
          "type": "category",
          "label": "WS-Security",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/ws-security-from-target",
            "develop/policies/ws-security-to-target",
            "develop/policies/ws-security-username-token",
            "develop/policies/ws-security-encryption",
            "develop/policies/ws-decrypt",
            "develop/policies/ws-security-signing",
            "develop/policies/ws-security-signature-verification",
            "develop/policies/ws-security-timestamp",
            "develop/policies/ws-security-token"
          ]
        },
        {
          "type": "category",
          "label": "Token Service",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/policies/token-service/overview",
            "develop/policies/token-service/token-acquisition-methods",
            "develop/policies/token-service/token-introspection-revocation-discovery",
            "develop/policies/token-service/manual-token-generation-and-validation",
            "develop/policies/token-service/token-faq"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Monitoring and Analytics",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/monitoring-analysis/step-by-step-tracing",
        "develop/monitoring-analysis/api-traffic",
        "develop/monitoring-analysis/analytics",
        "develop/monitoring-analysis/audit-records",
        "develop/monitoring-analysis/application-logs"
      ]
    },
    {
      "type": "category",
      "label": "Global Settings",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/global-configurations/global-policies",
        "develop/global-configurations/policy-groups",
        "develop/global-configurations/global-settings-group",
        "develop/environment-variables"
      ]
    },
    {
      "type": "category",
      "label": "Test and Tools",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/test-debug-tools/test-console",
        {
          "type": "category",
          "label": "Toolbox",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/test-debug-tools/toolbox/json-transformer",
            "develop/test-debug-tools/toolbox/jsonpath-test",
            "develop/test-debug-tools/toolbox/xml-transformer",
            "develop/test-debug-tools/toolbox/xpath-test",
            "develop/test-debug-tools/toolbox/data-operations"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Deployment and Version",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/deployment-and-version-management"
      ]
    }
  ],
  "management": [
    {
      "type": "category",
      "label": "Management",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/overview"
      ]
    },
    {
      "type": "category",
      "label": "User & Access",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/user-access-management/overview",
        "admin/user-access-management/roles",
        "admin/user-access-management/users",
        "admin/user-access-management/teams",
        "admin/user-access-management/role-permission-details",
        "admin/user-access-management/authorization-matrix"
      ]
    },
    {
      "type": "category",
      "label": "Projects",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/project-management/overview",
        "admin/project-management/project-general-settings",
        "admin/project-management/project-members",
        "admin/project-management/project-creation"
      ]
    },
    {
      "type": "category",
      "label": "Identity & Security",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/identity-management/overview",
        {
          "type": "category",
          "label": "Credential Management",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/identity-management/credentials",
            "admin/identity-management/organizations",
            "admin/identity-management/ip-groups",
            "admin/identity-management/contracts-protocols",
            "admin/identity-management/credential-roles",
            "admin/identity-management/api-proxy-acl",
            "admin/identity-management/api-proxy-group-acl",
            "admin/identity-management/rate-limit-control-list"
          ]
        },
        {
          "type": "category",
          "label": "Identity Providers",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/identity-management/identity-providers/database-provider",
            "admin/identity-management/identity-providers/ldap-active-directory",
            "admin/identity-management/identity-providers/api-authentication-provider"
          ]
        },
        "admin/identity-management/acl-report"
      ]
    },
    {
      "type": "category",
      "label": "Secrets",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/secrets-management/overview",
        "admin/secrets-management/certificates",
        "admin/secrets-management/private-key-management",
        "admin/secrets-management/keystore-management",
        "admin/secrets-management/jwks-configuration",
        "admin/secrets-management/export-import"
      ]
    },
    {
      "type": "category",
      "label": "Servers and Infrastructures",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/server-management/gateway-runtimes",
        "admin/server-management/distributed-cache",
        "admin/server-management/environment-diagnostics",
        "admin/server-management/adding-connectors-to-gateway-environments",
        "admin/server-management/kubernetes-workloads",
        "admin/server-management/tcp-connectivity-test"
      ]
    },
    {
      "type": "category",
      "label": "System Settings",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/system-settings/overview",
        "admin/system-settings/system-settings-and-limits",
        "admin/system-settings/global-configuration",
        {
          "type": "category",
          "label": "Predefined Values",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/system-settings/predefined-values/cors-headers",
            "admin/system-settings/predefined-values/cors-origin-values",
            "admin/system-settings/predefined-values/filter-rules",
            "admin/system-settings/predefined-values/http-request-header-names",
            "admin/system-settings/predefined-values/http-request-header-values",
            "admin/system-settings/predefined-values/byte-array-content-types"
          ]
        },
        "admin/system-settings/ldap-login-settings",
        "admin/system-settings/login-log-connector-configuration",
        "admin/system-settings/license-management",
        "admin/system-settings/error-messages",
        "admin/system-settings/ip-geolocation-setting",
        "admin/system-settings/token-management-settings"
      ]
    },
    {
      "type": "category",
      "label": "Audit & Compliance",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/audit-compliance/overview",
        "admin/audit-compliance/audit-records",
        "admin/audit-compliance/token-requests",
        "admin/audit-compliance/login-records",
        "admin/audit-compliance/application-log-cleanup-tasks",
        "admin/audit-compliance/application-logs"
      ]
    },
    {
      "type": "category",
      "label": "API Promotion",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/api-promotion/overview",
        "admin/api-promotion/instance-management",
        "admin/api-promotion/api-mapping-creation",
        "admin/api-promotion/execution-and-monitoring",
        "admin/api-promotion/best-practices"
      ]
    },
    {
      "type": "category",
      "label": "Scheduled Jobs",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/scheduled-jobs"
      ]
    },
    {
      "type": "category",
      "label": "Integrations",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "integrations/connection-management/overview",
        "integrations/connection-management/activeMQ",
        "integrations/connection-management/database",
        "integrations/connection-management/email",
        "integrations/connection-management/elasticsearch",
        "integrations/connection-management/elasticsearch-monitor",
        "integrations/connection-management/ldap-active-directory",
        "integrations/connection-management/kafka",
        "integrations/connection-management/rabbitMQ",
        "integrations/connection-management/elasticsearch-configuration",
        "integrations/connection-management/ftp",
        "integrations/connection-management/graylog",
        "integrations/connection-management/linux",
        "integrations/connection-management/logback",
        "integrations/connection-management/snmp",
        "integrations/connection-management/syslog",
        "integrations/connection-management/webhook",
        {
          "type": "category",
          "label": "API Integrator (Task Flow Builder)",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "integrations/api-integrator-task-flow-builder/overview",
            "integrations/api-integrator-task-flow-builder/task-flow-design",
            "integrations/api-integrator-task-flow-builder/taskflow-monitor"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Connectors",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "integrations/connectors/overview",
        "integrations/connectors/database-connector",
        "integrations/connectors/kafka-connector",
        "integrations/connectors/rabbitmq-connector",
        "integrations/connectors/activemq-connector",
        "integrations/connectors/api-call-connector",
        "integrations/connectors/email-connector",
        "integrations/connectors/ftp-list-connector",
        "integrations/connectors/ftp-read-connector",
        "integrations/connectors/elasticsearch-connector",
        "integrations/connectors/script-connector",
        "integrations/connectors/webhook-connector",
        "integrations/connectors/api-call",
        "integrations/connectors/notification-connector",
        "integrations/connectors/snmp-connector",
        "integrations/connectors/syslog-connector",
        "integrations/connectors/logback-connector",
        "integrations/connectors/linux-script-connector"
      ]
    },
    {
      "type": "category",
      "label": "Analytics Reports",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/analytics-reports/api-traffic-time-metrics"
      ]
    }
  ],
  "analytics-and-monitoring": [
    {
      "type": "category",
      "label": "Analytics",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/analytics",
        "analytic/dashboard",
        "analytic/api-traffic",
        "analytic/query-editor/queries",
        "analytic/query-editor/filters",
        "analytic/tracing"
      ]
    },
    {
      "type": "category",
      "label": "API Traffic Settings",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/api-traffic-log-settings",
        "analytic/transfer-unsent-api-traffic-logs",
        "analytic/api-traffic-log-record-data-structure"
      ]
    },
    {
      "type": "category",
      "label": "Reports",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/analytics-reports/reports",
        "analytic/analytics-reports/api-traffic-over-time",
        "analytic/analytics-reports/api-proxy-creation-report",
        "analytic/analytics-reports/api-endpoint-creation-report",
        "analytic/analytics-reports/api-traffic-and-time-metrics",
        "analytic/analytics-reports/endpoint-traffic-and-time-metrics",
        "analytic/analytics-reports/endpoint-size-metrics",
        "analytic/analytics-reports/client-traffic-and-time-metrics",
        "analytic/analytics-reports/ip-traffic-and-time-metrics",
        "analytic/analytics-reports/report-generator",
        "analytic/analytics-reports/endpoints-not-receiving-requests",
        "analytic/analytics-reports/clients-not-making-requests",
        "analytic/analytics-reports/client-route-report"
      ]
    },
    {
      "type": "category",
      "label": "Monitoring",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "monitor/overview",
        "monitor/api-health-check",
        "monitor/anomaly-detector",
        "monitor/alarm"
      ]
    }
  ],
  "api-portal": [
    {
      "type": "category",
      "label": "API Developer Portal",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "api-portal/overview",
        "api-portal/portal-overview",
        "api-portal/api-portal-settings",
        "api-portal/api-multi-portal-usage",
        "api-portal/appearance-theme",
        "api-portal/api-product",
        "api-portal/api-product-categories",
        "api-portal/frequently-asked-questions",
        "api-portal/accounts-developers",
        "api-portal/approval-requests",
        "api-portal/application-management",
        "api-portal/jira-integration",
        "api-portal/api-product-application-registrations",
        "api-portal/login-logs",
        "api-portal/api-product-view-history",
        "api-portal/organization-visibility",
        "api-portal/support-packages",
        "api-portal/support-package-content",
        "api-portal/support-package-type",
        "api-portal/support-package-requests",
        "api-portal/tools",
        "api-portal/responsible-unit",
        {
          "type": "category",
          "label": "MCP Usage",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "api-portal/mcp-usage/mcp-overview",
            "api-portal/mcp-usage/claude-desktop-mcp-integration",
            "api-portal/mcp-usage/claude-desktop-mcp-connection",
            "api-portal/mcp-usage/web-browser-mcp-connection"
          ]
        }
      ]
    }
  ],
  "operations": [
    {
      "type": "category",
      "label": "Operations",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/overview"
      ]
    },
    {
      "type": "category",
      "label": "Backup and Restore",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/backup-and-restore/backup",
        "operations/backup-and-restore/restore",
        "operations/backup-and-restore/mongodb-backup-and-restore"
      ]
    },
    {
      "type": "category",
      "label": "Maintenance and Optimization",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/healthcheck-version-addresses",
        "operations/diagnostic-endpoint-addresses",
        {
          "type": "category",
          "label": "Database Growth Management",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/database-growth-management/overview",
            "operations/database-growth-management/apinizer-log-collection-cleanup",
            "operations/database-growth-management/audit-event-collection-cleanup",
            "operations/database-growth-management/history-acl-collection-cleanup",
            "operations/database-growth-management/alert-history-collection-cleanup",
            "operations/database-growth-management/log-tokentraffic-collection-cleanup",
            "operations/database-growth-management/anomaly-detector-result-collection-cleanup",
            "operations/database-growth-management/uptime-monitor-result-collection-cleanup",
            "operations/database-growth-management/taskflow-execution-log-collection-cleanup",
            "operations/database-growth-management/report-configuration-result-collection-cleanup",
            "operations/database-growth-management/trace-log-collections-cleanup",
            "operations/database-growth-management/user-token-blacklist-collection-cleanup",
            "operations/database-growth-management/notification-user-collection-cleanup",
            "operations/database-growth-management/tcp-connectivity-test-history-collection-cleanup",
            "operations/database-growth-management/persistent-audit-event-collection-cleanup",
            "operations/database-growth-management/portal-login-logs-collection-cleanup"
          ]
        },
        {
          "type": "category",
          "label": "Common Problems and Solutions",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/common-problems-solutions/apinizer-issues",
            "operations/common-problems-solutions/api-proxy-deployment-issues",
            "operations/common-problems-solutions/high-latency-slow-response-times",
            "operations/common-problems-solutions/authentication-failures",
            "operations/common-problems-solutions/database-connection-issues",
            "operations/common-problems-solutions/memory-leaks-oom-errors",
            "operations/common-problems-solutions/policy-execution-failures",
            "operations/common-problems-solutions/routing-issues",
            "operations/common-problems-solutions/ssl-tls-certificate-issues",
            "operations/common-problems-solutions/performance-degradation"
          ]
        },
        {
          "type": "category",
          "label": "Useful Commands",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/useful-commands/kubernetes-docker-containerd",
            "operations/useful-commands/mongodb",
            "operations/useful-commands/elasticsearch"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Operation Guides",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Administrator Guide",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/administrator-guides/api-manager-ldap-integration",
            {
              "type": "category",
              "label": "Starting Apinizer Modules with SSL/TLS",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/administrator-guides/ssl-tls-starting-apinizer-modules",
                "operations/administrator-guides/api-manager-ssl"
              ]
            },
            "operations/administrator-guides/kubernetes-ingress-apinizer-access",
            "operations/administrator-guides/apinizer-pod-auto-scaling",
            "operations/administrator-guides/mongodb-automatic-backup",
            "operations/administrator-guides/pfx-to-jks-conversion",
            "operations/administrator-guides/server-ip-change",
            "operations/administrator-guides/kubernetes-cluster-ip-change",
            "operations/administrator-guides/pod-thread-count-periodic-monitoring",
            "operations/administrator-guides/jvm-garbage-collector-tuning",
            "operations/administrator-guides/multi-env-deployment-pipeline",
            "operations/administrator-guides/gateway-performance-tuning",
            "operations/administrator-guides/geolocation-city-based-access-control",
            "operations/administrator-guides/kibana-maps-geographic-visualization",
            "operations/administrator-guides/apinizer-log-table-creation-commands",
            "operations/administrator-guides/apinizer-reverse-proxy-kubectl-connection-windows",
            "operations/administrator-guides/prometheus-zabbix-integration",
            {
              "type": "category",
              "label": "Prometheus and Grafana Integration",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/administrator-guides/prometheus-grafana-integration",
                {
                  "type": "category",
                  "label": "Gateway Metrics Integration",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "operations/administrator-guides/gateway-metrics-integration/gateway-metrics-overview",
                    "operations/administrator-guides/gateway-metrics-integration/gateway-prometheus-scraping",
                    "operations/administrator-guides/gateway-metrics-integration/gateway-promql-examples",
                    "operations/administrator-guides/gateway-metrics-integration/gateway-grafana-dashboard"
                  ]
                },
                {
                  "type": "category",
                  "label": "Cache Metrics Integration",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "operations/administrator-guides/cache-metrics-integration/cache-metrics-overview",
                    "operations/administrator-guides/cache-metrics-integration/cache-prometheus-scraping",
                    "operations/administrator-guides/cache-metrics-integration/cache-promql-examples",
                    "operations/administrator-guides/cache-metrics-integration/cache-grafana-dashboard"
                  ]
                },
                "operations/administrator-guides/grafana-prometheus-data-source"
              ]
            },
            {
              "type": "category",
              "label": "Syslog Integration",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/administrator-guides/syslog-integration",
                "operations/administrator-guides/traffic-logs-syslog-transfer",
                "operations/administrator-guides/system-logs-syslog-transfer"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Troubleshooting",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Linux",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/troubleshooting/linux-troubleshooting",
            "operations/troubleshooting/linux-disk-expansion"
          ]
        },
        {
          "type": "category",
          "label": "Kubernetes",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/troubleshooting/kubernetes-docker-containerd-troubleshooting",
            "operations/troubleshooting/kubernetes-certificate-check-renewal",
            "operations/kubernetes/kubernetes-docker-containerd-commands",
            {
              "type": "category",
              "label": "Private/Local Docker Registry Usage",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/kubernetes/private-docker-registry-on-centos-7"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "MongoDB",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/troubleshooting/mongodb-troubleshooting",
            "operations/troubleshooting/writing-mongodb-logs-to-elasticsearch"
          ]
        },
        {
          "type": "category",
          "label": "Elasticsearch",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/troubleshooting/elasticsearch-troubleshooting/general",
            "operations/troubleshooting/elasticsearch-troubleshooting/dumping-specific-api-proxy-logs",
            "operations/troubleshooting/elasticsearch-troubleshooting/curator-operations",
            "operations/troubleshooting/elasticsearch-troubleshooting/elasticsearch-reindex-operation",
            "operations/troubleshooting/elasticsearch-troubleshooting/slow-first-query-issue",
            "operations/troubleshooting/elasticsearch-troubleshooting/saving-all-scroll-api-results-to-file"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Log Analysis Guide",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/log-analysis-guide/log-locations",
        "operations/log-analysis-guide/log-levels-filtering",
        "operations/log-analysis-guide/log-pattern-analysis",
        "operations/log-analysis-guide/kibana-log-search",
        "operations/log-analysis-guide/alerting-on-log-patterns"
      ]
    }
  ],
  "guides": [
    {
      "type": "category",
      "label": "Guides",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "tutorials/overview",
        {
          "type": "category",
          "label": "API Proxy Scenarios",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-proxy-scenarios/rest-api-security-manager-plain-text-auth",
            "tutorials/api-proxy-scenarios/rest-api-security-manager-basic-auth",
            "tutorials/api-proxy-scenarios/rest-api-security-manager-jwt-auth",
            "tutorials/api-proxy-scenarios/rest-api-security-manager-oauth2-auth",
            "tutorials/api-proxy-scenarios/rest-api-ldap-plain-text-auth",
            "tutorials/api-proxy-scenarios/rest-api-database-plain-text-auth",
            "tutorials/api-proxy-scenarios/soap-security-manager-plain-text-auth",
            "tutorials/api-proxy-scenarios/mysql-db2api-creation",
            "tutorials/api-proxy-scenarios/mock-api-json-transformation-script",
            "tutorials/api-proxy-scenarios/mtls-authentication",
            "tutorials/api-proxy-scenarios/jwt-validation",
            "tutorials/api-proxy-scenarios/variable-content-based-throttling",
            "tutorials/api-proxy-scenarios/json-schema-validation-rest-to-soap",
            "tutorials/api-proxy-scenarios/json-schema-validation-rest",
            "tutorials/api-proxy-scenarios/api-based-throttling-fixed-time-intervals",
            "tutorials/api-proxy-scenarios/api-based-quota-fixed-time-intervals",
            "tutorials/api-proxy-scenarios/custom-variable-map-business-rule",
            "tutorials/api-proxy-scenarios/api-proxy-http-websocket-policy-condition"
          ]
        },
        {
          "type": "category",
          "label": "API Creator",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-creator-scenarios/db2api-select-usage",
            "tutorials/api-creator-scenarios/db2api-stored-procedure-calling",
            "tutorials/api-creator-scenarios/db2api-update-usage",
            "tutorials/api-creator-scenarios/db2api-insert-usage",
            "tutorials/api-creator-scenarios/db2api-batch-insert-usage",
            "tutorials/api-creator-scenarios/mock-api-usage",
            "tutorials/api-creator-scenarios/script2api-usage"
          ]
        },
        {
          "type": "category",
          "label": "API Integrator",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-integrator-scenarios/task-to-task-json-data-transfer",
            "tutorials/api-integrator-scenarios/task-to-task-xml-data-transfer",
            "tutorials/api-integrator-scenarios/task-to-task-soap-xml-data-transfer",
            "tutorials/api-integrator-scenarios/script-task-resultmap-data-transfer"
          ]
        },
        {
          "type": "category",
          "label": "API Monitoring",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-monitoring-scenarios/uptime-monitor-usage",
            {
              "type": "category",
              "label": "Anomaly Detector Usage",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/api-monitoring-scenarios/anomaly-detector-usage",
                "tutorials/api-monitoring-scenarios/failed-request-rate-increase-anomaly-detection"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "API Analytics and Observability",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-analytics-and-observability-scenarios/kibana-api-traffic-log-visualization",
            "tutorials/api-analytics-and-observability-scenarios/kibana-8-17-10-api-traffic-log-visualization"
          ]
        },
        {
          "type": "category",
          "label": "API Portal",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-portal-scenarios/api-portal-on-api-developer-operations",
            "tutorials/api-portal-scenarios/api-portal-api-manager-operations"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "How-To Guides",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Developer Guides",
          "collapsed": true,
          "collapsible": true,
          "items": [
            {
              "type": "category",
              "label": "Groovy Usage (Script Policy)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/developer-guides/groovy-usage/groovy-basic-examples",
                "tutorials/how-to-guides/developer-guides/groovy-usage/copy-body-to-header",
                "tutorials/how-to-guides/developer-guides/groovy-usage/api-call-and-process-result",
                "tutorials/how-to-guides/developer-guides/groovy-usage/api-call-form-urlencoded",
                "tutorials/how-to-guides/developer-guides/groovy-usage/xmlslurper-soap-message-preparation",
                "tutorials/how-to-guides/developer-guides/groovy-usage/jsonslurper-add-field-to-rest-body",
                "tutorials/how-to-guides/developer-guides/groovy-usage/sending-email-with-json",
                "tutorials/how-to-guides/developer-guides/groovy-usage/sending-email-from-soap-message",
                "tutorials/how-to-guides/developer-guides/groovy-usage/api-call-xml-json-message-creation",
                "tutorials/how-to-guides/developer-guides/groovy-usage/xmlslurper-soap-parse-field-manipulation",
                "tutorials/how-to-guides/developer-guides/groovy-usage/read-request-url-path-change-backend-address",
                "tutorials/how-to-guides/developer-guides/groovy-usage/api-call-and-process",
                "tutorials/how-to-guides/developer-guides/groovy-usage/change-xml-node-level",
                "tutorials/how-to-guides/developer-guides/groovy-usage/jsonslurper-rest2soap-response-processing",
                "tutorials/how-to-guides/developer-guides/groovy-usage/json-quote-cleaning",
                "tutorials/how-to-guides/developer-guides/groovy-usage/combining-two-services",
                "tutorials/how-to-guides/developer-guides/groovy-usage/db2api-masked-data-transfer",
                "tutorials/how-to-guides/developer-guides/groovy-usage/jwt-payload-data-extraction",
                "tutorials/how-to-guides/developer-guides/groovy-usage/getting-username-from-authorization-header",
                "tutorials/how-to-guides/developer-guides/groovy-usage/map-foreach-loop",
                "tutorials/how-to-guides/developer-guides/groovy-usage/json-turkish-id-number-validation",
                "tutorials/how-to-guides/developer-guides/groovy-usage/convert-json-request-to-form-data",
                "tutorials/how-to-guides/developer-guides/groovy-usage/soap-message-signature-verification",
                "tutorials/how-to-guides/developer-guides/groovy-usage/soap-message-signing",
                "tutorials/how-to-guides/developer-guides/groovy-usage/xmlslurper-soap-header-add-value",
                "tutorials/how-to-guides/developer-guides/groovy-usage/disable-ssl-verification-pkix-error",
                "tutorials/how-to-guides/developer-guides/groovy-usage/oidc-integration",
                "tutorials/how-to-guides/developer-guides/groovy-usage/xml-to-json-unicode-normalization",
                "tutorials/how-to-guides/developer-guides/groovy-usage/add-element-to-xml-body-child",
                "tutorials/how-to-guides/developer-guides/groovy-usage/dynamic-xml-to-json-script",
                "tutorials/how-to-guides/developer-guides/groovy-usage/base64-pdf-decode-browser",
                "tutorials/how-to-guides/developer-guides/groovy-usage/obtaining-a-token-with-ntlm"
              ]
            },
            {
              "type": "category",
              "label": "Javascript Usage (Script Policy)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/developer-guides/javascript-usage/api-call",
                "tutorials/how-to-guides/developer-guides/javascript-usage/api-call-apinizer-endpoint",
                "tutorials/how-to-guides/developer-guides/javascript-usage/cbs-response-body-url-change"
              ]
            },
            {
              "type": "category",
              "label": "Jolt Usage (Json Transformation Policy)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/developer-guides/jolt-usage/extract-data-change-key",
                "tutorials/how-to-guides/developer-guides/jolt-usage/simplify-db2api-result",
                "tutorials/how-to-guides/developer-guides/jolt-usage/edit-procedure-result",
                "tutorials/how-to-guides/developer-guides/jolt-usage/combine-two-data-results",
                "tutorials/how-to-guides/developer-guides/jolt-usage/remove-desired-field",
                "tutorials/how-to-guides/developer-guides/jolt-usage/json2json-performance-comparison",
                "tutorials/how-to-guides/developer-guides/jolt-usage/edit-key-value-pairs",
                "tutorials/how-to-guides/developer-guides/jolt-usage/convert-string-key-to-numeric",
                "tutorials/how-to-guides/developer-guides/jolt-usage/add-remove-key-expression",
                "tutorials/how-to-guides/developer-guides/jolt-usage/add-key-value-if-missing",
                "tutorials/how-to-guides/developer-guides/jolt-usage/convert-string-to-long",
                "tutorials/how-to-guides/developer-guides/jolt-usage/convert-field-to-array"
              ]
            },
            {
              "type": "category",
              "label": "XSLT Usage (Xml Transformation Policy)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-info-to-soap-header",
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-fixed-values-to-soap-message",
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-security-fields-to-soap-header",
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-field-to-soap-message",
                "tutorials/how-to-guides/developer-guides/xslt-usage/extract-header-body-content",
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-static-value-to-first-method",
                "tutorials/how-to-guides/developer-guides/xslt-usage/resolve-id-reference-issue",
                "tutorials/how-to-guides/developer-guides/xslt-usage/remove-all-xml-attributes",
                "tutorials/how-to-guides/developer-guides/xslt-usage/send-wsa-setting-with-specific-value",
                "tutorials/how-to-guides/developer-guides/xslt-usage/clean-soap-message-content",
                "tutorials/how-to-guides/developer-guides/xslt-usage/add-prefix-to-selected-xml-elements",
                "tutorials/how-to-guides/developer-guides/xslt-usage/convert-soap11-to-soap12"
              ]
            },
            {
              "type": "category",
              "label": "Message Builder Usage (Message Builder Policy)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/developer-guides/message-builder-usage/value-copy-and-merging",
                "tutorials/how-to-guides/developer-guides/message-builder-usage/conditional-value-assignment",
                "tutorials/how-to-guides/developer-guides/message-builder-usage/json-body-enrichment",
                "tutorials/how-to-guides/developer-guides/message-builder-usage/jexl-script-array-processing"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Administrator Guides",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/how-to-guides/administrator-guides/api-manager-ldap-integration",
            {
              "type": "category",
              "label": "Starting Apinizer Modules with SSL/TLS",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/administrator-guides/api-manager-ssl"
              ]
            },
            "tutorials/how-to-guides/administrator-guides/kubernetes-ingress-apinizer-access",
            "tutorials/how-to-guides/administrator-guides/apinizer-pod-auto-scaling",
            "tutorials/how-to-guides/administrator-guides/mongodb-automatic-backup",
            "tutorials/how-to-guides/administrator-guides/pfx-to-jks-conversion",
            "tutorials/how-to-guides/administrator-guides/server-ip-change",
            "tutorials/how-to-guides/administrator-guides/kubernetes-cluster-ip-change",
            "tutorials/how-to-guides/administrator-guides/pod-thread-count-periodic-monitoring",
            "tutorials/how-to-guides/administrator-guides/manual-monitoring",
            "tutorials/how-to-guides/administrator-guides/geolocation-city-based-access-control",
            "tutorials/how-to-guides/administrator-guides/kibana-maps-geographic-visualization",
            {
              "type": "category",
              "label": "Prometheus and Grafana Integration",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/administrator-guides/prometheus-grafana-integration",
                {
                  "type": "category",
                  "label": "Gateway Metrics Integration",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "tutorials/how-to-guides/administrator-guides/gateway-metrics-integration/gateway-metrics-overview",
                    "tutorials/how-to-guides/administrator-guides/gateway-metrics-integration/gateway-prometheus-scraping",
                    "tutorials/how-to-guides/administrator-guides/gateway-metrics-integration/gateway-promql-examples",
                    "tutorials/how-to-guides/administrator-guides/gateway-metrics-integration/gateway-grafana-dashboard"
                  ]
                },
                {
                  "type": "category",
                  "label": "Cache Metrics Integration",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "tutorials/how-to-guides/administrator-guides/cache-metrics-integration/cache-metrics-overview",
                    "tutorials/how-to-guides/administrator-guides/cache-metrics-integration/cache-prometheus-scraping",
                    "tutorials/how-to-guides/administrator-guides/cache-metrics-integration/cache-promql-examples",
                    "tutorials/how-to-guides/administrator-guides/cache-metrics-integration/cache-grafana-dashboard"
                  ]
                },
                "tutorials/how-to-guides/administrator-guides/grafana-prometheus-data-source"
              ]
            },
            {
              "type": "category",
              "label": "Syslog Integration",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/administrator-guides/syslog-integration",
                "tutorials/how-to-guides/administrator-guides/traffic-logs-syslog-transfer",
                "tutorials/how-to-guides/administrator-guides/system-logs-syslog-transfer"
              ]
            },
            {
              "type": "category",
              "label": "Apinizer Jenkins Pipeline Integration",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/how-to-guides/administrator-guides/github-actions-jenkins-apinizer-pipeline"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Articles",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "articles/apinizer-api-portal-mcp-integration",
        "articles/rate-limit-throttling-quota-management",
        "articles/rate-limit-control-list-rlcl",
        "articles/api-plan-and-rate-limit-control-list-rlcl-comparison",
        "articles/api-gateway-or-the-code-way",
        "articles/gateway-zoo-conways-law-api-event-kafka-ai-gateways",
        "articles/apinizer-prometheus-grafana-integration-guide",
        "articles/to-monitor-or-not-to-monitor",
        "articles/explaining-api-and-api-management-to-our-parents",
        "articles/understanding-enterprise-systems-airport-city-analogy",
        "articles/api-load-testing-performance-analysis-k6-jmeter",
        "articles/api-team-mantra",
        "articles/apinizer-active-active-architecture-eliminating-spof",
        "articles/no-security-without-api-gateway-right-order-guide"
      ]
    }
  ]
};

export default sidebars;
