/**
 * AUTO-GENERATED by scripts/convert-sidebars.mjs from docs.json.
 * Locale: tr
 * Each key on the default export corresponds to one Mintlify tab.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  "genel-bakis": [
    {
      "type": "category",
      "label": "Başlangıç",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "index",
        "quickstart"
      ]
    },
    {
      "type": "category",
      "label": "Apinizer'ı Anlamak",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "concepts/apinizer-nedir",
        "concepts/sektorel-faydalar",
        "concepts/rol-bazli-faydalar",
        "concepts/teknik-ozellikler",
        "concepts/mimari",
        {
          "type": "category",
          "label": "Dağıtım Topolojileri ve Planlama",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/deployment/genel-bakis",
            "concepts/deployment/yazilim",
            "concepts/deployment/kapasite-planlama",
            "concepts/deployment/deployment-modelleri",
            "concepts/deployment/topoloji-test-poc",
            "concepts/deployment/topoloji-profesyonel",
            "concepts/deployment/topoloji-ha",
            "concepts/deployment/kurulum-oncesi-oneriler",
            "concepts/deployment/ag-topolojisi",
            "concepts/deployment/ag-baglanti-matrisi",
            "concepts/deployment/antivirus-yapilandirmasi"
          ]
        },
        {
          "type": "category",
          "label": "Temel Kavramlar ve Terminoloji",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/temel-kavramlar/ortam-nedir",
            "concepts/temel-kavramlar/proje-nedir",
            "concepts/temel-kavramlar/api-proxy-nedir",
            "concepts/temel-kavramlar/politika-nedir",
            "concepts/temel-kavramlar/hata-mesaji-yapilandirma",
            "concepts/temel-kavramlar/mesaj-isleme-ve-politika-uygulama",
            "concepts/temel-kavramlar/icerik-kodlama-ve-sikistirma",
            "concepts/temel-kavramlar/kosullu-politika-calistirma",
            "concepts/temel-kavramlar/routing-ve-upstream",
            "concepts/temel-kavramlar/client-route",
            "concepts/temel-kavramlar/baglantilar",
            "concepts/temel-kavramlar/konnektor",
            "concepts/temel-kavramlar/endpoint",
            "concepts/temel-kavramlar/variable",
            "concepts/temel-kavramlar/dinamik-degiskenler",
            "concepts/temel-kavramlar/environment-variable",
            "concepts/temel-kavramlar/api-proxy-group"
          ]
        },
        {
          "type": "category",
          "label": "Temel Bileşenler",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/temel-bilesenler/api-manager",
            "concepts/temel-bilesenler/api-gateway",
            "concepts/temel-bilesenler/identity-manager",
            "concepts/temel-bilesenler/analytics-engine",
            "concepts/temel-bilesenler/api-portal",
            "concepts/temel-bilesenler/api-designer",
            "concepts/temel-bilesenler/api-creator",
            "concepts/temel-bilesenler/api-integrator",
            "concepts/temel-bilesenler/onbellek-bileseni",
            "concepts/temel-bilesenler/izleme-bileseni"
          ]
        },
        {
          "type": "category",
          "label": "Desteklenen Teknolojiler",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "concepts/desteklenen-teknolojiler/desteklenen-kutuphaneler",
            "concepts/desteklenen-teknolojiler/desteklenen-protokoller",
            "concepts/desteklenen-teknolojiler/desteklenen-veritabanlari"
          ]
        },
        "concepts/sozluk",
        "concepts/uyumluluk-ve-veri-koruma",
        "concepts/benchmark-sonuclari"
      ]
    }
  ],
  "surumler": [
    "release-notes/genel-bakis",
    "release-notes/degisiklik-gunlugu",
    "release-notes/surum-notlari-2026",
    "release-notes/surum-notlari-2025",
    "release-notes/surum-notlari-2024",
    "release-notes/surum-notlari-2023",
    "release-notes/surum-notlari-2022",
    "release-notes/surum-notlari-2021",
    "release-notes/destegi-sonlandirilanlar-ve-kaldirilanlar",
    "release-notes/yol-haritasi"
  ],
  "kurulum-ve-guncelleme": [
    {
      "type": "category",
      "label": "Kurulum",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "setup/kuruluma-genel-bakis",
        "setup/kubernetes",
        "setup/sanal-sunucu",
        {
          "type": "category",
          "label": "Docker Kurulumu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "setup/docker/genel-bakis",
            "setup/docker/all-in-one",
            "setup/docker/docker-compose",
            "setup/docker/apiportal"
          ]
        },
        {
          "type": "category",
          "label": "MongoDB Kurulumu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "setup/mongodb/ubuntu-mongodb",
            "setup/mongodb/rhel-mongodb"
          ]
        },
        "setup/gateway-ayarlari",
        "setup/kaldirma",
        "setup/sorun-giderme"
      ]
    },
    {
      "type": "category",
      "label": "Güncelleme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "upgrade/apinizer-surum-yukseltme",
        "upgrade/kubernetes-surum-yukseltme",
        "upgrade/mongodb-surum-yukseltme",
        "upgrade/elasticsearch-surum-yukseltme"
      ]
    },
    {
      "type": "category",
      "label": "Altyapı Bileşenleri Kurulumu",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Kubernetes Cluster Hazırlığı",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/kubernetes/ubuntu-kubernetes",
            "installation/kubernetes/rhel-kubernetes",
            "installation/kubernetes/kubernetes-metric-server",
            "installation/kubernetes/kubernetes-high-availability-yuksek-erisim-cluster",
            "installation/kubernetes/kubernetes-dashboard",
            "installation/kubernetes/prometheus-grafana",
            "installation/kubernetes/argocd-ile-versiyon-yonetimi"
          ]
        },
        {
          "type": "category",
          "label": "Elasticsearch (opsiyonel)",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/elasticsearch/ubuntu-elasticsearch",
            "installation/elasticsearch/ubuntu-elasticsearch-8.17.10",
            "installation/elasticsearch/rhel-elasticsearch",
            "installation/elasticsearch/rhel-elasticsearch-8.17.10",
            "installation/elasticsearch/basit-kimlik-dogrulama",
            "installation/elasticsearch/yetki-gereksinimleri",
            "installation/elasticsearch/yedekleme-politikasi",
            "installation/elasticsearch/manuel-ilm-politikasi-ve-template-olusturma"
          ]
        },
        {
          "type": "category",
          "label": "Bulut Sağlayıcılar",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/bulut/amazon-eks-elastic-kubernetes-service",
            "installation/bulut/microsoft-aks-azure-kubernetes-service",
            "installation/bulut/openshift-origin-311"
          ]
        },
        {
          "type": "category",
          "label": "Çevrimdışı Kurulum",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "installation/offline/giris",
            "installation/offline/ubuntu",
            "installation/offline/rhel-8x",
            "installation/offline/rhel-9x"
          ]
        }
      ]
    }
  ],
  "api-leri-yonetme": [
    {
      "type": "category",
      "label": "API Geliştirme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/quick-start",
        {
          "type": "category",
          "label": "API Tasarımı",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-tasarimi/spec-designer",
            "develop/api-tasarimi/data-models"
          ]
        },
        "develop/api-listesi-yonetimi",
        {
          "type": "category",
          "label": "API Proxy Oluşturma",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-proxy-olusturma/client-route-ayarlari",
            "develop/api-proxy-olusturma/api-proxy-olusturma",
            "develop/api-proxy-olusturma/rest-api-proxy-olusturma",
            "develop/api-proxy-olusturma/soap-api-proxy-olusturma",
            "develop/api-proxy-olusturma/soaprest-api-proxy-olusturma",
            "develop/api-proxy-olusturma/websocket-api-proxy-olusturma",
            "develop/api-proxy-olusturma/grpc-api-proxy-olusturma",
            "develop/api-proxy-olusturma/api-creator-db-api-olusturma",
            "develop/api-proxy-olusturma/api-creator-script-api-olusturma",
            "develop/api-proxy-olusturma/api-creator-mock-api-olusturma",
            "develop/api-proxy-olusturma/connector-api-proxy-olusturma",
            "develop/api-proxy-olusturma/coklu-schema-port-wsdl"
          ]
        },
        "develop/api-proxy-group-olusturma",
        {
          "type": "category",
          "label": "API Proxy Konfigürasyonu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/api-proxy-konfigurasyonu/overview",
            "develop/api-proxy-konfigurasyonu/settings",
            "develop/api-proxy-konfigurasyonu/design",
            "develop/api-proxy-konfigurasyonu/endpoint-konfigurasyonu",
            "develop/api-proxy-konfigurasyonu/soap-metod-konfigurasyonu",
            "develop/api-proxy-konfigurasyonu/politika-yonetimi",
            "develop/api-proxy-konfigurasyonu/api-trafik-log-ayarlari",
            "develop/api-proxy-konfigurasyonu/yukleme-ve-tanim-dosyasi-bilgileri",
            "develop/api-proxy-konfigurasyonu/client-route"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Yönlendirme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/yonlendirme/http-yonlendirme",
        "develop/yonlendirme/grpc-yonlendirme",
        "develop/yonlendirme/websocket-yonlendirme",
        "develop/yonlendirme/tekrar-deneme-ve-yuk-devretme",
        "develop/yonlendirme/canary-ve-traffic-mirroring",
        "develop/yonlendirme/kalici-oturum"
      ]
    },
    {
      "type": "category",
      "label": "Politikalar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Kimlik Doğrulama",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/plain-text",
            "develop/politikalar/digest-kimlik-dogrulama",
            "develop/politikalar/basic-kimlik-dogrulama",
            "develop/politikalar/jwt",
            "develop/politikalar/oauth2",
            "develop/politikalar/oidc",
            "develop/politikalar/mTLS",
            "develop/politikalar/backend-kimlik-dogrulama",
            "develop/politikalar/jose-dogrulama",
            "develop/politikalar/jose-uygulama-politikasi",
            "develop/politikalar/saml"
          ]
        },
        {
          "type": "category",
          "label": "Erişim Kontrolü",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/izin-verilen-ip-listesi",
            "develop/politikalar/yasakli-ip-listesi",
            "develop/politikalar/istemci-yasaklama",
            "develop/politikalar/zaman-kisitlamasi",
            "develop/politikalar/api-bazli-daraltma",
            "develop/politikalar/api-bazli-kota"
          ]
        },
        {
          "type": "category",
          "label": "Mesaj Doğrulama",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/dijital-imza",
            "develop/politikalar/dijital-imza-dogrulama",
            "develop/politikalar/sifreleme",
            "develop/politikalar/mesaj-akisi-ve-politika-yonetimi",
            "develop/politikalar/log",
            "develop/politikalar/sifre-acma",
            "develop/politikalar/json-sema-dogrulama",
            "develop/politikalar/xml-sema-dogrulama",
            "develop/politikalar/max-mesaj",
            "develop/politikalar/min-mesaj"
          ]
        },
        {
          "type": "category",
          "label": "Dönüştürme ve İşleme",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/json-donusturme",
            "develop/politikalar/xml-donusturme",
            "develop/politikalar/script",
            "develop/politikalar/is-kurali",
            "develop/politikalar/icerik-filtresi",
            "develop/politikalar/api-cagrisi",
            "develop/politikalar/onbellekleme",
            "develop/politikalar/redaction",
            "develop/politikalar/loglama",
            "develop/politikalar/mesaj-olusturucu"
          ]
        },
        {
          "type": "category",
          "label": "WS-Security",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/ws-gelen-mesaj",
            "develop/politikalar/ws-giden-mesaj",
            "develop/politikalar/ws-kimlik-dogrulama",
            "develop/politikalar/ws-sifreleme",
            "develop/politikalar/ws-decrypt",
            "develop/politikalar/ws-guvenlik-imzalama",
            "develop/politikalar/ws-guvenlik-imza-dogrulama",
            "develop/politikalar/ws-timestamp",
            "develop/politikalar/ws-token"
          ]
        },
        {
          "type": "category",
          "label": "Token Servisi",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/politikalar/token-service/genel-bakis",
            "develop/politikalar/token-service/token-alma-yontemleri",
            "develop/politikalar/token-service/token-sorgulama-iptal-kesif",
            "develop/politikalar/token-service/manuel-token-uretimi-ve-validasyonu",
            "develop/politikalar/token-service/token-sss"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "İzleme ve Analiz",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/izleme-analiz/adim-adim-izleme",
        "develop/izleme-analiz/api-trafigi",
        "develop/izleme-analiz/analitik",
        "develop/izleme-analiz/islem-kayitlari",
        "develop/izleme-analiz/uygulama-loglari"
      ]
    },
    {
      "type": "category",
      "label": "Global Ayarlar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/global-configurations/global-policies",
        "develop/global-configurations/policy-groups",
        "develop/global-configurations/global-settings-group",
        "develop/environment-variables"
      ]
    },
    {
      "type": "category",
      "label": "Test ve Araçlar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/test-debug-araclari/test-console",
        {
          "type": "category",
          "label": "Araç Kutusu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "develop/test-debug-araclari/toolbox/json-transformer",
            "develop/test-debug-araclari/toolbox/jsonpath-test",
            "develop/test-debug-araclari/toolbox/xml-transformer",
            "develop/test-debug-araclari/toolbox/xpath-test",
            "develop/test-debug-araclari/toolbox/data-operations"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Yükleme ve Sürüm",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "develop/yukleme-ve-surum-yonetimi"
      ]
    }
  ],
  "yonetim": [
    {
      "type": "category",
      "label": "Yönetim",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/genel-bakis"
      ]
    },
    {
      "type": "category",
      "label": "Kullanıcı & Erişim",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/user-access-management/genel-bakis",
        "admin/user-access-management/kullanicilar",
        "admin/user-access-management/takimlar",
        "admin/user-access-management/rol-yetki-detaylari",
        "admin/user-access-management/yetkilendirme-matrisi",
        "admin/user-access-management/rol"
      ]
    },
    {
      "type": "category",
      "label": "Projeler",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/project-management/genel-bakis",
        "admin/project-management/proje-genel-ayarlari",
        "admin/project-management/proje-uyeleri",
        "admin/project-management/proje-olusturma"
      ]
    },
    {
      "type": "category",
      "label": "Kimlik & Güvenlik",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/identity-management/genel-bakis",
        {
          "type": "category",
          "label": "Kimlik Bilgisi Yönetimi",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/identity-management/kimlik-bilgileri",
            "admin/identity-management/kurumlar",
            "admin/identity-management/sozlesmeler-protokoller",
            "admin/identity-management/ip-guruplari",
            "admin/identity-management/kimlik-bilgisi-rolleri",
            "admin/identity-management/api-proxy-acl",
            "admin/identity-management/api-proxy-grup-acl",
            "admin/identity-management/rate-limit-kontrol-listesi"
          ]
        },
        {
          "type": "category",
          "label": "Kimlik Sağlayıcılar",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/identity-management/identity-providers/database-provider",
            "admin/identity-management/identity-providers/ldap-active-directory",
            "admin/identity-management/identity-providers/api-authentication-provider"
          ]
        },
        "admin/identity-management/acl-raporu"
      ]
    },
    {
      "type": "category",
      "label": "Gizlilik",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/secrets-management/genel-bakis",
        "admin/secrets-management/sertifikalar",
        "admin/secrets-management/ozel-anahtar-yonetimi",
        "admin/secrets-management/keystore-yonetimi",
        "admin/secrets-management/jwks-yapilandirma",
        "admin/secrets-management/export-import"
      ]
    },
    {
      "type": "category",
      "label": "Sunucular ve Altyapılar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/server-management/gateway-runtime-lari",
        "admin/server-management/dagitik-cache",
        "admin/server-management/environment-diagnostics",
        "admin/server-management/gateway-ortamlarina-konnektor-eklenmesi",
        "admin/server-management/kubernetes-is-yukleri",
        "admin/server-management/tcp-baglanti-testi"
      ]
    },
    {
      "type": "category",
      "label": "Sistem Ayarları",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/system-settings/genel-bakis",
        "admin/system-settings/sistem-ayarlari-ve-limitler",
        "admin/system-settings/global-yapilandirma",
        {
          "type": "category",
          "label": "Ön Tanımlı Değerler",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "admin/system-settings/on-tanimli-degerler/cors-basliklari",
            "admin/system-settings/on-tanimli-degerler/cors-orijin-degerleri",
            "admin/system-settings/on-tanimli-degerler/filtre-kurallari",
            "admin/system-settings/on-tanimli-degerler/http-istek-baslik-adlari",
            "admin/system-settings/on-tanimli-degerler/http-istek-baslik-degerleri",
            "admin/system-settings/on-tanimli-degerler/byte-array-content-types"
          ]
        },
        "admin/system-settings/ldap-ile-giris-ayarlari",
        "admin/system-settings/login-log-konnektor-yapilandirmasi",
        "admin/system-settings/lisans-yonetimi",
        "admin/system-settings/hata-mesajlari",
        "admin/system-settings/ip-geolocation-ayari",
        "admin/system-settings/token-yonetim-ayarlari"
      ]
    },
    {
      "type": "category",
      "label": "Denetim & Uyumluluk",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/audit-compliance/genel-bakis",
        "admin/audit-compliance/denetim-kayitlari",
        "admin/audit-compliance/token-istekleri",
        "admin/audit-compliance/giris-kayitlari",
        "admin/audit-compliance/audit-records",
        "admin/audit-compliance/application-logs",
        "admin/audit-compliance/uygulama-logu-temizleme-gorevleri"
      ]
    },
    {
      "type": "category",
      "label": "API Promotion",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/api-promotion/genel-bakis",
        "admin/api-promotion/instance-yonetimi",
        "admin/api-promotion/api-mapping-olusturma",
        "admin/api-promotion/calistirma-ve-izleme",
        "admin/api-promotion/en-iyi-uygulamalar"
      ]
    },
    {
      "type": "category",
      "label": "Zamanlanmış İşler",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/zamanlanmis-isler"
      ]
    },
    {
      "type": "category",
      "label": "Entegrasyonlar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "integrations/baglanti-yonetimi/genel-bakis",
        "integrations/baglanti-yonetimi/activeMQ",
        "integrations/baglanti-yonetimi/database",
        "integrations/baglanti-yonetimi/email",
        "integrations/baglanti-yonetimi/elasticsearch",
        "integrations/baglanti-yonetimi/elasticsearch-monitor",
        "integrations/baglanti-yonetimi/ldap-active-directory",
        "integrations/baglanti-yonetimi/elasticsearch-configuration",
        "integrations/baglanti-yonetimi/kafka",
        "integrations/baglanti-yonetimi/rabbitMQ",
        "integrations/baglanti-yonetimi/ftp",
        "integrations/baglanti-yonetimi/graylog",
        "integrations/baglanti-yonetimi/linux",
        "integrations/baglanti-yonetimi/logback",
        "integrations/baglanti-yonetimi/snmp",
        "integrations/baglanti-yonetimi/syslog",
        "integrations/baglanti-yonetimi/webhook",
        {
          "type": "category",
          "label": "API Integrator (Task Flow Builder)",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "integrations/api-integrator-task-flow-builder/genel-bakis",
            "integrations/api-integrator-task-flow-builder/task-flow-tasarimi",
            "integrations/api-integrator-task-flow-builder/taskflow-monitor"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Konnektörler",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "integrations/konnektorler/genel-bakis",
        "integrations/konnektorler/database-konnektor",
        "integrations/konnektorler/kafka-konnektor",
        "integrations/konnektorler/rabbitmq-konnektor",
        "integrations/konnektorler/activemq-konnektor",
        "integrations/konnektorler/api-call-konnektor",
        "integrations/konnektorler/email-konnektor",
        "integrations/konnektorler/ftp-list-konnektor",
        "integrations/konnektorler/api-call",
        "integrations/konnektorler/ftp-read-konnektor",
        "integrations/konnektorler/elasticsearch-konnektor",
        "integrations/konnektorler/script-konnektor",
        "integrations/konnektorler/webhook-konnektor",
        "integrations/konnektorler/notification-konnektor",
        "integrations/konnektorler/snmp-konnektor",
        "integrations/konnektorler/syslog-konnektor",
        "integrations/konnektorler/logback-konnektor",
        "integrations/konnektorler/linux-script-konnektor"
      ]
    },
    {
      "type": "category",
      "label": "Analitik Raporları",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "admin/analytics-reports/api-trafigi-(zaman-metrikleri)"
      ]
    }
  ],
  "analitik-ve-i-zleme": [
    {
      "type": "category",
      "label": "Analitik",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/analytics",
        "analytic/dashboard",
        "analytic/api-trafigi",
        "analytic/query-editor/sorgular-queries",
        "analytic/query-editor/filtreler-filters",
        "analytic/tracing"
      ]
    },
    {
      "type": "category",
      "label": "API Trafiği Ayarları",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/api-traffic-log-ayarlari",
        "analytic/gonderilmemis-api-trafik-loglari-tasima",
        "analytic/api-trafigi-log-kaydi-veri-yapisi"
      ]
    },
    {
      "type": "category",
      "label": "Raporlar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "analytic/analytics-reports/raporlar",
        "analytic/analytics-reports/api-trafigi-zamana-gore",
        "analytic/analytics-reports/api-proxy-olusturma-raporu",
        "analytic/analytics-reports/api-endpoint-olusturma-raporu",
        "analytic/analytics-reports/api-trafigi-ve-zaman-metrikleri",
        "analytic/analytics-reports/endpoint-trafigi-ve-zaman-metrikleri",
        "analytic/analytics-reports/endpoint-boyut-metrikleri",
        "analytic/analytics-reports/istemci-trafigi-ve-zaman-metrikleri",
        "analytic/analytics-reports/ip-trafigi-ve-zaman-metrikleri",
        "analytic/analytics-reports/rapor-uretici",
        "analytic/analytics-reports/istek-almayan-endpoint'ler",
        "analytic/analytics-reports/istek-atmayan-client'lar",
        "analytic/analytics-reports/client-route-raporu"
      ]
    },
    {
      "type": "category",
      "label": "İzleme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "monitor/izleme-genel-bakis",
        "monitor/api-saglik-kontrolu",
        "monitor/anomali-tespit-edici",
        "monitor/alarm"
      ]
    }
  ],
  "api-portal": [
    {
      "type": "category",
      "label": "API Geliştirici Portal",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "api-portal/genel-bakis",
        "api-portal/portal-overview",
        "api-portal/api-portal-ayarlari",
        "api-portal/api-multi-portal-kullanimi",
        "api-portal/gorunum-tema",
        "api-portal/api-urunu",
        "api-portal/api-urun-kategorileri",
        "api-portal/sss",
        "api-portal/hesaplar-gelistiriciler",
        "api-portal/onay-istekleri",
        "api-portal/uygulama-yonetimi",
        "api-portal/jira-entegrasyonu",
        "api-portal/api-urun-uygulama-kayitlari",
        "api-portal/giris-kayitlari",
        "api-portal/api-urun-goruntulenme-gecmisi",
        "api-portal/organizasyon-gorunurlugu",
        "api-portal/destek-paketleri",
        "api-portal/destek-paketi-icerigi",
        "api-portal/destek-paketi-tipi",
        "api-portal/destek-paketi-istekleri",
        "api-portal/araclar",
        "api-portal/sorumlu-birim",
        {
          "type": "category",
          "label": "MCP Kullanımı",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "api-portal/mcp-kullanimi/mcp-genel-bakis",
            "api-portal/mcp-kullanimi/claude-desktop-mcp-entegrasyonu",
            "api-portal/mcp-kullanimi/claude-desktop-mcp-baglantisi",
            "api-portal/mcp-kullanimi/web-tarayici-mcp-baglantisi"
          ]
        }
      ]
    }
  ],
  "operasyon": [
    {
      "type": "category",
      "label": "Operasyon",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/genel-bakis"
      ]
    },
    {
      "type": "category",
      "label": "Yedekleme ve Geri Yükleme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/yedek-ve-geri-yukleme/yedekleme",
        "operations/yedek-ve-geri-yukleme/geri-yukleme",
        "operations/yedek-ve-geri-yukleme/mongodb-yedekleme-ve-geri-yukleme"
      ]
    },
    {
      "type": "category",
      "label": "Bakım ve Optimizasyon",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/healthcheck-versiyon-adresleri",
        "operations/diagnostic-endpoint-adresleri",
        {
          "type": "category",
          "label": "Veritabanı Büyüme Yönetimi",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/database-buyume-yonetimi/genel-bakis",
            "operations/database-buyume-yonetimi/apinizer-log-collection-temizleme",
            "operations/database-buyume-yonetimi/audit-event-collection-temizleme",
            "operations/database-buyume-yonetimi/history-acl-collection-temizleme",
            "operations/database-buyume-yonetimi/alert-history-collection-temizleme",
            "operations/database-buyume-yonetimi/log-tokentraffic-collection-temizleme",
            "operations/database-buyume-yonetimi/anomaly-detector-result-collection-temizleme",
            "operations/database-buyume-yonetimi/uptime-monitor-result-collection-temizleme",
            "operations/database-buyume-yonetimi/taskflow-execution-log-collection-temizleme",
            "operations/database-buyume-yonetimi/report-configuration-result-collection-temizleme",
            "operations/database-buyume-yonetimi/trace-log-collections-temizleme",
            "operations/database-buyume-yonetimi/user-token-blacklist-collection-temizleme",
            "operations/database-buyume-yonetimi/notification-user-collection-temizleme",
            "operations/database-buyume-yonetimi/tcp-connectivity-test-history-collection-temizleme",
            "operations/database-buyume-yonetimi/persistent-audit-event-collection-temizleme",
            "operations/database-buyume-yonetimi/portal-login-logs-collection-temizleme"
          ]
        },
        {
          "type": "category",
          "label": "Yaygın Sorunlar ve Çözümleri",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/yaygin-sorunlar-cozumleri/apinizer-sorunlari",
            "operations/yaygin-sorunlar-cozumleri/api-proxy-deployment-issues",
            "operations/yaygin-sorunlar-cozumleri/high-latency-slow-response-times",
            "operations/yaygin-sorunlar-cozumleri/authentication-failures",
            "operations/yaygin-sorunlar-cozumleri/database-connection-issues",
            "operations/yaygin-sorunlar-cozumleri/memory-leaks-oom-errors",
            "operations/yaygin-sorunlar-cozumleri/policy-execution-failures",
            "operations/yaygin-sorunlar-cozumleri/routing-issues",
            "operations/yaygin-sorunlar-cozumleri/ssl-tls-certificate-issues",
            "operations/yaygin-sorunlar-cozumleri/performance-degradation"
          ]
        },
        {
          "type": "category",
          "label": "Faydalı Komutlar",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/faydali-komutlar/kubernetes-docker-containerd",
            "operations/faydali-komutlar/mongodb",
            "operations/faydali-komutlar/elasticsearch"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Operasyon Kılavuzları",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Yönetici Kılavuzu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/yonetici-kilavuzlari/api-manager-ldap-entegrasyonu",
            {
              "type": "category",
              "label": "SSL/TLS ile Apinizer Modüllerini Başlatma",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/yonetici-kilavuzlari/ssl-tls-apinizer-modulleri-baslatma",
                "operations/yonetici-kilavuzlari/api-manager-ssl"
              ]
            },
            "operations/yonetici-kilavuzlari/kubernetes-ingress-apinizer-erisimi",
            "operations/yonetici-kilavuzlari/apinizer-pod-auto-scaling",
            "operations/yonetici-kilavuzlari/mongodb-otomatik-yedekleme",
            "operations/yonetici-kilavuzlari/pfx-jks-donusturme",
            "operations/yonetici-kilavuzlari/bilesen-ip-degisiminde-etkiler-ve-mudahale",
            "operations/yonetici-kilavuzlari/pod-thread-sayisi-periyodik-izleme",
            "operations/yonetici-kilavuzlari/jvm-garbage-collector-ayarlama",
            "operations/yonetici-kilavuzlari/multi-env-deployment-pipeline",
            "operations/yonetici-kilavuzlari/gateway-performans-ayarlama",
            "operations/yonetici-kilavuzlari/geolocation-sehir-bazli-erisim-kontrolu",
            "operations/yonetici-kilavuzlari/kibana-maps-cografi-gorsellestirme",
            "operations/yonetici-kilavuzlari/apinizer-log-tablolari-olusturma-komutlari",
            "operations/yonetici-kilavuzlari/apinizer-reverse-proxy-ile-kubectl-baglantisi-windows",
            "operations/yonetici-kilavuzlari/prometheus-zabbix-entegrasyonu",
            {
              "type": "category",
              "label": "Prometheus ve Grafana Entegrasyonu",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/yonetici-kilavuzlari/prometheus-grafana-entegrasyonu",
                {
                  "type": "category",
                  "label": "Gateway Metrics Entegrasyonu",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "operations/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-metrics-genel-bakis",
                    "operations/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-prometheus-scraping",
                    "operations/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-promql-ornekleri",
                    "operations/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-grafana-dashboard"
                  ]
                },
                {
                  "type": "category",
                  "label": "Cache Metrics Entegrasyonu",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "operations/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-metrics-genel-bakis",
                    "operations/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-prometheus-scraping",
                    "operations/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-promql-ornekleri",
                    "operations/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-grafana-dashboard"
                  ]
                },
                "operations/yonetici-kilavuzlari/grafana-prometheus-data-source"
              ]
            },
            {
              "type": "category",
              "label": "Syslog Entegrasyonu",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "operations/yonetici-kilavuzlari/syslog-entegrasyonu",
                "operations/yonetici-kilavuzlari/traffic-loglar-syslog-aktarma",
                "operations/yonetici-kilavuzlari/system-loglar-syslog-aktarma"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Container Registry",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/container-registry/container-imajlari-ve-registry",
        "operations/container-registry/nexus-kullanimi",
        "operations/container-registry/harbor-kullanimi",
        "operations/container-registry/private-registry-kurulumu"
      ]
    },
    {
      "type": "category",
      "label": "Sorun Giderme",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Linux",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/sorun-giderme/linux-sorunlari",
            "operations/sorun-giderme/linux-disk-genisletme"
          ]
        },
        {
          "type": "category",
          "label": "Kubernetes",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/sorun-giderme/kubernetes-docker-containerd-sorunlari",
            "operations/sorun-giderme/kubernetes-sertifika-kontrol-yenileme",
            "operations/kubernetes/ansible-ile-ubuntu-uzerinde-kubernetes"
          ]
        },
        {
          "type": "category",
          "label": "MongoDB",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/sorun-giderme/mongodb-sorunlari",
            "operations/sorun-giderme/mongodb-loglarini-elasticsearch-yazma"
          ]
        },
        {
          "type": "category",
          "label": "Elasticsearch",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "operations/sorun-giderme/elasticsearch-sorunlari/genel",
            "operations/sorun-giderme/elasticsearch-sorunlari/belirli-api-proxy-loglarini-dump-etme",
            "operations/sorun-giderme/elasticsearch-sorunlari/curator-islemleri",
            "operations/sorun-giderme/elasticsearch-sorunlari/elasticsearch-reindex-islemi",
            "operations/sorun-giderme/elasticsearch-sorunlari/yavas-ilk-arama-sorunu",
            "operations/sorun-giderme/elasticsearch-sorunlari/scroll-api-tum-sonuclari-dosyaya-kaydetme"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Log Analizi Kılavuzu",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "operations/log-analizi-kilavuzu/log-locations",
        "operations/log-analizi-kilavuzu/log-levels-filtering",
        "operations/log-analizi-kilavuzu/log-pattern-analysis",
        "operations/log-analizi-kilavuzu/kibana-log-search",
        "operations/log-analizi-kilavuzu/alerting-on-log-patterns"
      ]
    }
  ],
  "kilavuzlar": [
    {
      "type": "category",
      "label": "Kılavuzlar",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "tutorials/genel-bakis",
        {
          "type": "category",
          "label": "API Proxy Senaryoları",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-proxy-senaryolari/rest-api-security-manager-plain-text-auth",
            "tutorials/api-proxy-senaryolari/rest-api-security-manager-basic-auth",
            "tutorials/api-proxy-senaryolari/rest-api-security-manager-jwt-auth",
            "tutorials/api-proxy-senaryolari/rest-api-security-manager-oauth2-auth",
            "tutorials/api-proxy-senaryolari/rest-api-ldap-plain-text-auth",
            "tutorials/api-proxy-senaryolari/rest-api-database-plain-text-auth",
            "tutorials/api-proxy-senaryolari/soap-security-manager-plain-text-auth",
            "tutorials/api-proxy-senaryolari/mysql-db2api-olusturma",
            "tutorials/api-proxy-senaryolari/mock-api-json-transformation-script",
            "tutorials/api-proxy-senaryolari/mtls-kimlik-dogrulama",
            "tutorials/api-proxy-senaryolari/jwt-validasyonu",
            "tutorials/api-proxy-senaryolari/degisken-icerige-gore-throttling",
            "tutorials/api-proxy-senaryolari/json-schema-validation-rest-to-soap",
            "tutorials/api-proxy-senaryolari/json-schema-validation-rest",
            "tutorials/api-proxy-senaryolari/api-based-throttling-sabit-zaman",
            "tutorials/api-proxy-senaryolari/api-based-quota-sabit-zaman",
            "tutorials/api-proxy-senaryolari/custom-variable-map-business-rule",
            "tutorials/api-proxy-senaryolari/api-proxy-http-websocket-politika-kosulu"
          ]
        },
        {
          "type": "category",
          "label": "API Oluşturucu",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-olusturucu-senaryolari/db2api-select-kullanimi",
            "tutorials/api-olusturucu-senaryolari/db2api-stored-procedure-cagirma",
            "tutorials/api-olusturucu-senaryolari/db2api-update-kullanimi",
            "tutorials/api-olusturucu-senaryolari/db2api-insert-kullanimi",
            "tutorials/api-olusturucu-senaryolari/db2api-batch-insert-kullanimi",
            "tutorials/api-olusturucu-senaryolari/mock-api-kullanimi",
            "tutorials/api-olusturucu-senaryolari/script2api-kullanimi"
          ]
        },
        {
          "type": "category",
          "label": "API Entegratör",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-entegrator-senaryolari/gorevler-arasi-json-veri-aktarimi",
            "tutorials/api-entegrator-senaryolari/gorevler-arasi-xml-veri-aktarimi",
            "tutorials/api-entegrator-senaryolari/gorevler-arasi-soap-xml-veri-aktarimi",
            "tutorials/api-entegrator-senaryolari/script-gorevi-resultmap-veri-aktarimi"
          ]
        },
        {
          "type": "category",
          "label": "API İzleme",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-izleme-senaryolari/calisma-suresini-izleme-kullanimi",
            {
              "type": "category",
              "label": "Anomali Dedektörü Kullanımı",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/api-izleme-senaryolari/anomali-dedektoru-kullanimi",
                "tutorials/api-izleme-senaryolari/basarisiz-istek-orani-artisinda-anomali-tespiti"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "API Analitiği ve Gözlemlenebilirlik",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-analitigi-ve-gozlemlenebilirlik-senaryolari/kibana-api-trafik-log-gorsellestirme",
            "tutorials/api-analitigi-ve-gozlemlenebilirlik-senaryolari/kibana-8-17-10-api-trafik-log-gorsellestirme"
          ]
        },
        {
          "type": "category",
          "label": "API Portal",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/api-portal-senaryolari/api-portal-uzerinde-api-developer-islemleri",
            "tutorials/api-portal-senaryolari/api-portal-uzerinde-api-manager-islemleri",
            "tutorials/api-portal-senaryolari/api-portal-api-manager-islemleri"
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Nasıl Yapılır Kılavuzları",
      "collapsed": false,
      "collapsible": true,
      "items": [
        {
          "type": "category",
          "label": "Geliştirici Kılavuzları",
          "collapsed": true,
          "collapsible": true,
          "items": [
            {
              "type": "category",
              "label": "Groovy Kullanımı (Script Politikası)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/groovy-temel-ornekler",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/body-header-kopyalama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/api-cagrisi-yapmak-ve-islemek",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/api-cagrisi-form-urlencoded",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xmlslurper-soap-mesaj-hazirlama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/jsonslurper-rest-body-alan-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/json-formatinda-mail-atma",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/soap-mesaj-uzerinden-mail",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/api-cagrisi-xml-json-mesaj-olusturma",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xmlslurper-soap-parse-alanlara-mudahale",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/request-url-path-backend-degistirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xml-node-seviyesi-degistirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/jsonslurper-rest2soap-yanit-isleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/json-tirnak-temizleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/iki-servis-birlestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/db2api-maskeli-veri-iletimi",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/jwt-payload-veri-alma",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/map-foreach-dongusu",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/json-tc-kimlik-no-kontrolu",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/json-request-form-data-cevirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/soap-mesaj-imza-dogrulama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/soap-mesaj-imzalama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xmlslurper-soap-header-deger-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/pkix-hatasi-ssl-devre-disi",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/oidc-entegrasyonu",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xml-to-json-unicode-normallestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/xml-body-alt-elemana-element-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/dinamik-xml-2-json-scripti",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/base64-pdf-decode-tarayici",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/ntlm-ile-token-alma",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/groovy-kullanimi/jwt-den-username-alma"
              ]
            },
            {
              "type": "category",
              "label": "Javascript Kullanımı (Script Politikası)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/javascript-kullanimi/api-cagrisi",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/javascript-kullanimi/api-cagrisi-apinizer-uc-nokta",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/javascript-kullanimi/cbs-response-body-url-degistirme"
              ]
            },
            {
              "type": "category",
              "label": "Jolt Kullanımı (Json Dönüşüm Politikası)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/veri-cekme-key-degistirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/db2api-sonuc-sadelestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/procedure-sonuc-duzenleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/iki-data-birlestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/istenilen-alani-silme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/json2json-performans-kiyaslama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/key-value-duzenleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/string-numeric-cevirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/key-ifadesi-ekleme-silme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/key-degeri-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/string-long-cevirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/jolt-kullanimi/field-array-cevirme"
              ]
            },
            {
              "type": "category",
              "label": "XSLT Kullanımı (Xml Dönüşüm Politikası)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-header-bilgi-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-mesaj-sabit-degerler",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-header-security-alanlari",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-mesaj-alan-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/header-body-icerik-ayiklama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-mesaj-statik-deger",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/id-referans-sorunu-cozme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/xml-attributes-kaldirma",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/wsa-ayar-belirli-deger",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-mesaj-temizleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/xml-element-prefix-ekleme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/xslt-kullanimi/soap-11-12-donusum"
              ]
            },
            {
              "type": "category",
              "label": "Mesaj Oluşturucu Kullanımı (Mesaj Oluşturucu Politikası)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/mesaj-olusturucu-kullanimi/deger-kopyalama-ve-birlestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/mesaj-olusturucu-kullanimi/kosullu-deger-atama",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/mesaj-olusturucu-kullanimi/json-body-zenginlestirme",
                "tutorials/nasil-yapilir-kilavuzlari/develop-kilavuzlari/mesaj-olusturucu-kullanimi/jexl-script-dizi-isleme"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Yönetici Kılavuzları",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/api-manager-ldap-entegrasyonu",
            {
              "type": "category",
              "label": "SSL/TLS ile Apinizer Modüllerini Başlatma",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/api-manager-ssl"
              ]
            },
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/kubernetes-ingress-apinizer-erisimi",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/apinizer-pod-auto-scaling",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/mongodb-otomatik-yedekleme",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/pfx-jks-donusturme",
            "operations/yonetici-kilavuzlari/bilesen-ip-degisiminde-etkiler-ve-mudahale",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/pod-thread-sayisi-periyodik-izleme",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/manual-monitoring",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/geolocation-sehir-bazli-erisim-kontrolu",
            "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/kibana-maps-cografi-gorsellestirme",
            {
              "type": "category",
              "label": "Prometheus ve Grafana Entegrasyonu",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/prometheus-grafana-entegrasyonu",
                {
                  "type": "category",
                  "label": "Gateway Metrics Entegrasyonu",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-metrics-genel-bakis",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-prometheus-scraping",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-promql-ornekleri",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/gateway-metrics-entegrasyonu/gateway-grafana-dashboard"
                  ]
                },
                {
                  "type": "category",
                  "label": "Cache Metrics Entegrasyonu",
                  "collapsed": true,
                  "collapsible": true,
                  "items": [
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-metrics-genel-bakis",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-prometheus-scraping",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-promql-ornekleri",
                    "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/cache-metrics-entegrasyonu/cache-grafana-dashboard"
                  ]
                },
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/grafana-prometheus-data-source"
              ]
            },
            {
              "type": "category",
              "label": "Syslog Entegrasyonu",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/syslog-entegrasyonu",
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/traffic-loglar-syslog-aktarma",
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/system-loglar-syslog-aktarma"
              ]
            },
            {
              "type": "category",
              "label": "Apinizer Jenkins Pipeline Entegrasyonu",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "tutorials/nasil-yapilir-kilavuzlari/yonetici-kilavuzlari/github-actions-jenkins-apinizer-pipeline"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Makaleler",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "articles/apinizer-api-portal-mcp-entegrasyonu",
        "articles/rate-limit-throttling-quota-management",
        "articles/rate-limit-kontrol-listesi-rlcl",
        "articles/api-plan-ve-rate-limit-kontrol-listesi-rlcl-karsilastirmasi",
        "articles/api-gateway-or-the-code-way",
        "articles/gateway-hayvanat-bahcesi-conway-yasasi",
        "articles/apinizer-prometheus-grafana-entegrasyonu-rehber",
        "articles/to-monitor-or-not-to-monitor",
        "articles/annemize-ve-babamiza-api-ve-api-yonetimini-anlatmak",
        "articles/kurumsal-sistemleri-anlamak-havalimani-sehir-analojisi",
        "articles/api-yuk-testi-performans-analizi-k6-jmeter",
        "articles/api-ekibi-mantrasi",
        "articles/apinizer-aktif-aktif-mimari-spof-riski",
        "articles/api-gateway-olmadan-guvenlik-olmaz-dogru-siralama-rehberi",
        "articles/apinizer-rate-limit-mekanizmalari-karsilastirmasi"
      ]
    }
  ]
};

export default sidebars;
