/**
 * AUTO-GENERATED by scripts/convert-sidebars.mjs from docs.json.
 * Locale: api-reference
 * Each key on the default export corresponds to one Mintlify tab.
 */
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  "api-reference": [
    {
      "type": "category",
      "label": "Home",
      "collapsed": false,
      "collapsible": true,
      "items": [
        "getting-started/overview",
        "getting-started/overview-details",
        "getting-started/authentication",
        "getting-started/base-url",
        "getting-started/error-handling",
        "overview",
        "auth",
        {
          "type": "category",
          "label": "Projects",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "projects",
            "projects/list-projects"
          ]
        },
        {
          "type": "category",
          "label": "Environments",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "environments",
            "environments/list-environments",
            "environments/get-environments-by-project"
          ]
        },
        {
          "type": "category",
          "label": "API Proxies",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "api-proxies",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/crud/list-api-proxies",
                "api-proxies/crud/get-api-proxy",
                "api-proxies/crud/create-api-proxy-from-url",
                "api-proxies/crud/create-api-proxy-from-file",
                "api-proxies/crud/update-api-proxy",
                "api-proxies/crud/update-api-proxy-from-url",
                "api-proxies/crud/update-api-proxy-from-file",
                "api-proxies/crud/delete-api-proxy",
                "api-proxies/crud/export-api-proxy",
                "api-proxies/crud/import-api-proxy",
                "api-proxies/crud/import-api-proxy-and-override",
                "api-proxies/crud/import-api-proxy-without-override",
                "api-proxies/crud/get-invoke-info"
              ]
            },
            {
              "type": "category",
              "label": "Deployment",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/deployment",
                "api-proxies/deployment/deploy-api-proxy",
                "api-proxies/deployment/undeploy-api-proxy",
                "api-proxies/deployment/list-deploy-history",
                "api-proxies/deployment/get-deploy-history-detail",
                "api-proxies/deployment/delete-deploy-history",
                "api-proxies/deployment/rollback-deploy-history",
                "api-proxies/deployment/get-deploy-status",
                "api-proxies/deployment/get-route-health"
              ]
            },
            {
              "type": "category",
              "label": "Endpoints",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/endpoints",
                "api-proxies/endpoints/list-endpoints",
                "api-proxies/endpoints/get-endpoint",
                "api-proxies/endpoints/create-endpoint",
                "api-proxies/endpoints/update-endpoint",
                "api-proxies/endpoints/delete-endpoint",
                "api-proxies/endpoints/update-endpoint-status",
                "api-proxies/endpoints/update-endpoint-cache",
                "api-proxies/endpoints/update-endpoint-wsa",
                "api-proxies/endpoints/list-endpoint-policies"
              ]
            },
            {
              "type": "category",
              "label": "Methods",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/endpoints/list-methods",
                "api-proxies/endpoints/get-method-policies"
              ]
            },
            {
              "type": "category",
              "label": "Settings",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/settings",
                "api-proxies/settings/update-cors-settings",
                "api-proxies/settings/update-cache-settings",
                "api-proxies/settings/update-client-route",
                "api-proxies/settings/update-routing-addresses",
                "api-proxies/settings/update-routing-status",
                "api-proxies/settings/update-connection-settings",
                "api-proxies/settings/update-circuit-breaker-settings",
                "api-proxies/settings/update-proxy-server-settings",
                "api-proxies/settings/update-mtls-settings",
                "api-proxies/settings/update-ntlm-settings",
                "api-proxies/settings/update-traffic-log-settings",
                "api-proxies/settings/update-maintenance-mode",
                "api-proxies/settings/update-trace-settings",
                "api-proxies/settings/update-api-keys",
                "api-proxies/settings/update-metadata",
                "api-proxies/settings/update-forwarded-ip-header",
                "api-proxies/settings/update-error-handling",
                "api-proxies/settings/update-custom-message",
                "api-proxies/settings/update-grpc-settings",
                "api-proxies/settings/update-websocket-settings",
                "api-proxies/settings/update-json-error-template",
                "api-proxies/settings/update-xml-error-template"
              ]
            },
            {
              "type": "category",
              "label": "Traffic Log Settings",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxies/traffic-log-settings/get-all",
                "api-proxies/traffic-log-settings/get-by-environment",
                "api-proxies/traffic-log-settings/update",
                "api-proxies/traffic-log-settings/update-method-override",
                "api-proxies/traffic-log-settings/delete-method-override"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Policies",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "policies/index",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "policies/crud",
                "policies/crud/list-policies",
                "policies/crud/add-policy",
                "policies/crud/update-policy",
                "policies/crud/delete-policy"
              ]
            },
            {
              "type": "category",
              "label": "Policy Types",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "policies/policies",
                "policies/policies/policy-api-authentication",
                "policies/policies/policy-api-based-quota",
                "policies/policies/policy-api-based-throttling",
                "policies/policies/policy-api-call",
                "policies/policies/policy-auth-basic",
                "policies/policies/policy-black-ip",
                "policies/policies/policy-business-rule",
                "policies/policies/policy-client-ban",
                "policies/policies/policy-auth-clear-text",
                "policies/policies/policy-content-filter",
                "policies/policies/policy-decryption",
                "policies/policies/policy-digital-sign",
                "policies/policies/policy-digital-sign-verification",
                "policies/policies/policy-auth-digest",
                "policies/policies/policy-encryption",
                "policies/policies/policy-group",
                "policies/policies/policy-jose-implementation",
                "policies/policies/policy-jose-validation",
                "policies/policies/policy-json-schema-validation",
                "policies/policies/policy-json-transformation",
                "policies/policies/policy-auth-jwt",
                "policies/policies/policy-max-message-size",
                "policies/policies/policy-min-message-size",
                "policies/policies/policy-auth-mtls",
                "policies/policies/policy-oidc",
                "policies/policies/policy-auth-oauth2",
                "policies/policies/policy-redaction",
                "policies/policies/policy-request-protocol-transformation",
                "policies/policies/policy-response-protocol-transformation",
                "policies/policies/policy-saml-validation",
                "policies/policies/policy-script",
                "policies/policies/policy-time-restriction",
                "policies/policies/policy-white-ip",
                "policies/policies/policy-ws-security-decrypt",
                "policies/policies/policy-ws-security-encrypt",
                "policies/policies/policy-ws-security-from-target",
                "policies/policies/policy-ws-security-sign",
                "policies/policies/policy-ws-security-sign-validation",
                "policies/policies/policy-ws-security-timestamp",
                "policies/policies/policy-ws-security-to-target",
                "policies/policies/policy-ws-security-username",
                "policies/policies/policy-xml-schema-validation",
                "policies/policies/policy-xml-transformation",
                "policies/policies/policy-message-builder",
                "policies/policies/policy-log"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Connections",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "connections/index",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "connections/crud",
                "connections/crud/create-connection",
                "connections/crud/delete-connection",
                "connections/crud/get-connection",
                "connections/crud/list-connections",
                "connections/crud/update-connection"
              ]
            },
            {
              "type": "category",
              "label": "Connection Types",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "connections/connections",
                "connections/connections/connection-email",
                "connections/connections/connection-kafka",
                "connections/connections/connection-elasticsearch",
                "connections/connections/connection-rabbitmq",
                "connections/connections/connection-ftp",
                "connections/connections/connection-graylog",
                "connections/connections/connection-syslog",
                "connections/connections/connection-webhook",
                "connections/connections/connection-logback",
                "connections/connections/connection-activemq",
                "connections/connections/connection-snmp",
                "connections/connections/connection-linux-script",
                "connections/connections/connection-database",
                "connections/connections/connection-ldap"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Credentials",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "credentials",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "credentials/crud",
                "credentials/crud/change-credential-password",
                "credentials/crud/create-credential",
                "credentials/crud/delete-credential",
                "credentials/crud/list-credentials",
                "credentials/crud/update-credential"
              ]
            },
            {
              "type": "category",
              "label": "Access Management",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "credentials/access",
                "credentials/access/get-granted-access-list",
                "credentials/access/grant-access",
                "credentials/access/revoke-access"
              ]
            },
            {
              "type": "category",
              "label": "Secrets",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "credentials/secrets",
                "credentials/secrets/remove-certificate",
                "credentials/secrets/remove-keystore",
                "credentials/secrets/remove-private-key",
                "credentials/secrets/remove-public-key",
                "credentials/secrets/remove-secret-key",
                "credentials/secrets/remove-truststore",
                "credentials/secrets/set-certificate",
                "credentials/secrets/set-keystore",
                "credentials/secrets/set-private-key",
                "credentials/secrets/set-public-key",
                "credentials/secrets/set-secret-key",
                "credentials/secrets/set-truststore"
              ]
            },
            {
              "type": "category",
              "label": "JWK Settings",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "credentials/jwk-settings",
                "credentials/jwk-settings/remove-jwk-encryption",
                "credentials/jwk-settings/remove-jwk-validation",
                "credentials/jwk-settings/set-jwk-encryption",
                "credentials/jwk-settings/set-jwk-validation"
              ]
            },
            {
              "type": "category",
              "label": "Token Settings",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "credentials/token-settings",
                "credentials/token-settings/reset-token-settings",
                "credentials/token-settings/set-token-settings"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Keys & Secrets",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "keys-secrets",
            {
              "type": "category",
              "label": "JWKs (JSON Web Keys)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "keys-secrets/crud/list-jwks",
                "keys-secrets/crud/get-jwk",
                "keys-secrets/crud/create-jwk",
                "keys-secrets/crud/update-jwk",
                "keys-secrets/crud/delete-jwk",
                "keys-secrets/crud/generate-jwk",
                "keys-secrets/crud/parse-jwk-from-url",
                "keys-secrets/crud/parse-jwk-from-clipboard",
                "keys-secrets/crud/parse-jwk-from-certificate",
                "keys-secrets/crud/parse-jwk-from-key",
                "keys-secrets/crud/parse-jwk-from-keystore"
              ]
            },
            {
              "type": "category",
              "label": "Keystores",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "keys-secrets/crud/list-keystores",
                "keys-secrets/crud/get-keystore",
                "keys-secrets/crud/create-keystore",
                "keys-secrets/crud/update-keystore",
                "keys-secrets/crud/delete-keystore",
                "keys-secrets/crud/export-keystore",
                "keys-secrets/crud/import-keystore"
              ]
            },
            {
              "type": "category",
              "label": "Keys (Crypto Keys)",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "keys-secrets/crud/list-keys",
                "keys-secrets/crud/get-key",
                "keys-secrets/crud/create-key",
                "keys-secrets/crud/update-key",
                "keys-secrets/crud/delete-key",
                "keys-secrets/crud/export-key",
                "keys-secrets/crud/import-key"
              ]
            },
            {
              "type": "category",
              "label": "Certificates",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "keys-secrets/crud/list-certificates",
                "keys-secrets/crud/get-certificate",
                "keys-secrets/crud/create-certificate",
                "keys-secrets/crud/update-certificate",
                "keys-secrets/crud/delete-certificate",
                "keys-secrets/crud/export-certificate",
                "keys-secrets/crud/get-truststore-certificates"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "API Proxy Groups",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "api-proxy-groups",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxy-groups/crud",
                "api-proxy-groups/crud/create-api-proxy-group",
                "api-proxy-groups/crud/delete-api-proxy-group",
                "api-proxy-groups/crud/list-api-proxy-groups",
                "api-proxy-groups/crud/update-api-proxy-group"
              ]
            },
            {
              "type": "category",
              "label": "Deployment",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxy-groups/deployment",
                "api-proxy-groups/deployment/deploy-api-proxy-group",
                "api-proxy-groups/deployment/undeploy-api-proxy-group",
                "api-proxy-groups/deployment/list-environments",
                "api-proxy-groups/deployment/list-deploy-history",
                "api-proxy-groups/deployment/get-deploy-history-detail",
                "api-proxy-groups/deployment/delete-deploy-history"
              ]
            },
            {
              "type": "category",
              "label": "Group Memberships",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "api-proxy-groups/api-proxies",
                "api-proxy-groups/api-proxies/add-api-proxy-to-group",
                "api-proxy-groups/api-proxies/remove-api-proxy-from-group"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "Environment Variables",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "environment-variables",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "environment-variables/crud",
                "environment-variables/crud/create-environment-variable",
                "environment-variables/crud/delete-environment-variable",
                "environment-variables/crud/get-environment-variable",
                "environment-variables/crud/list-environment-variables",
                "environment-variables/crud/update-environment-variable"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "IP Groups",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "ip-groups",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "ip-groups/crud",
                "ip-groups/crud/create-ip-group",
                "ip-groups/crud/delete-ip-group",
                "ip-groups/crud/update-ip-group"
              ]
            },
            {
              "type": "category",
              "label": "IP Membership",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "ip-groups/ips",
                "ip-groups/ips/add-ips-to-group",
                "ip-groups/ips/delete-ips-from-group",
                "ip-groups/ips/update-ips-in-group"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "RLCL",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "rlcl",
            {
              "type": "category",
              "label": "CRUD Operations",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "rlcl/crud",
                "rlcl/crud/create-rlcl",
                "rlcl/crud/delete-rlcl",
                "rlcl/crud/update-rlcl"
              ]
            },
            {
              "type": "category",
              "label": "Endpoints",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "rlcl/endpoints",
                "rlcl/endpoints/add-endpoints",
                "rlcl/endpoints/delete-endpoints",
                "rlcl/endpoints/update-endpoints"
              ]
            },
            {
              "type": "category",
              "label": "Conditions",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "rlcl/condition",
                "rlcl/condition/add-condition",
                "rlcl/condition/delete-condition",
                "rlcl/condition/update-condition"
              ]
            },
            {
              "type": "category",
              "label": "Credentials",
              "collapsed": true,
              "collapsible": true,
              "items": [
                "rlcl/credentials",
                "rlcl/credentials/add-credentials",
                "rlcl/credentials/delete-credentials",
                "rlcl/credentials/update-credentials"
              ]
            }
          ]
        },
        {
          "type": "category",
          "label": "GeoLocation",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "geolocation",
            "geolocation/enable-geolocation",
            "geolocation/disable-geolocation",
            "geolocation/upload-mmdb-file"
          ]
        },
        {
          "type": "category",
          "label": "AI Gateway",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "ai-gateway",
            { "type": "category", "label": "LLM Providers", "collapsed": true, "collapsible": true, "items": ["llm-providers", "llm-providers/list-llm-providers", "llm-providers/get-llm-provider", "llm-providers/create-llm-provider", "llm-providers/update-llm-provider", "llm-providers/delete-llm-provider"] },
            { "type": "category", "label": "Model Catalog", "collapsed": true, "collapsible": true, "items": ["llm-models", "llm-models/list-llm-models", "llm-models/get-llm-model", "llm-models/create-llm-model", "llm-models/update-llm-model", "llm-models/delete-llm-model"] },
            { "type": "category", "label": "VectorDB Connections", "collapsed": true, "collapsible": true, "items": ["vector-dbs", "vector-dbs/list-vector-dbs", "vector-dbs/get-vector-db", "vector-dbs/create-vector-db", "vector-dbs/update-vector-db", "vector-dbs/delete-vector-db", "vector-dbs/test-vector-db-connection"] },
            { "type": "category", "label": "Knowledge Bases", "collapsed": true, "collapsible": true, "items": ["knowledge-bases", "knowledge-bases/list-knowledge-bases", "knowledge-bases/get-knowledge-base", "knowledge-bases/create-knowledge-base", "knowledge-bases/update-knowledge-base", "knowledge-bases/delete-knowledge-base", "knowledge-bases/reindex-knowledge-base", { "type": "category", "label": "Documents", "collapsed": true, "collapsible": true, "items": ["knowledge-bases/documents/upload-document", "knowledge-bases/documents/list-documents", "knowledge-bases/documents/get-document", "knowledge-bases/documents/delete-document"] }] },
            { "type": "category", "label": "MCP Outbound Connections", "collapsed": true, "collapsible": true, "items": ["mcp-connections", "mcp-connections/list-mcp-connections", "mcp-connections/get-mcp-connection", "mcp-connections/create-mcp-connection", "mcp-connections/update-mcp-connection", "mcp-connections/delete-mcp-connection"] },
            { "type": "category", "label": "MCP Inbound Servers", "collapsed": true, "collapsible": true, "items": ["mcp-inbound-servers", "mcp-inbound-servers/list-mcp-inbound-servers", "mcp-inbound-servers/get-mcp-inbound-server", "mcp-inbound-servers/create-mcp-inbound-server", "mcp-inbound-servers/update-mcp-inbound-server", "mcp-inbound-servers/delete-mcp-inbound-server"] },
            { "type": "category", "label": "A2A Outbound Connections", "collapsed": true, "collapsible": true, "items": ["a2a-connections", "a2a-connections/list-a2a-connections", "a2a-connections/get-a2a-connection", "a2a-connections/create-a2a-connection", "a2a-connections/update-a2a-connection", "a2a-connections/delete-a2a-connection", "a2a-connections/test-a2a-connection", "a2a-connections/parse-a2a-skills"] },
            { "type": "category", "label": "A2A Inbound Agents", "collapsed": true, "collapsible": true, "items": ["a2a-inbound-agents", "a2a-inbound-agents/list-a2a-inbound-agents", "a2a-inbound-agents/get-a2a-inbound-agent", "a2a-inbound-agents/create-a2a-inbound-agent", "a2a-inbound-agents/update-a2a-inbound-agent", "a2a-inbound-agents/delete-a2a-inbound-agent"] },
            { "type": "category", "label": "AI Budgets", "collapsed": true, "collapsible": true, "items": ["ai-budgets", "ai-budgets/get-budget-scope-rules", "ai-budgets/get-budget-hierarchy", "ai-budgets/get-effective-limit", "ai-budgets/update-budget"] },
            { "type": "category", "label": "AI Privacy Presets", "collapsed": true, "collapsible": true, "items": ["ai-privacy-presets", "ai-privacy-presets/list-ai-privacy-presets", "ai-privacy-presets/get-ai-privacy-preset", "ai-privacy-presets/create-ai-privacy-preset", "ai-privacy-presets/update-ai-privacy-preset", "ai-privacy-presets/delete-ai-privacy-preset"] },
            { "type": "category", "label": "AI Prompt-Guard Presets", "collapsed": true, "collapsible": true, "items": ["ai-prompt-guard-presets", "ai-prompt-guard-presets/list-ai-prompt-guard-presets", "ai-prompt-guard-presets/get-ai-prompt-guard-preset", "ai-prompt-guard-presets/create-ai-prompt-guard-preset", "ai-prompt-guard-presets/update-ai-prompt-guard-preset", "ai-prompt-guard-presets/delete-ai-prompt-guard-preset"] },
            { "type": "category", "label": "AI Gateway Settings", "collapsed": true, "collapsible": true, "items": ["ai-gateway-settings", "ai-gateway-settings/get-ai-gateway-settings", "ai-gateway-settings/update-ai-gateway-settings"] }
          ]
        },
        {
          "type": "category",
          "label": "Reports",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "reports",
            "reports/api-report",
            "reports/organization-api-data-model-access-report"
          ]
        },
        {
          "type": "category",
          "label": "Test",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "test",
            "test/healthcheck",
            "test/secure-hello"
          ]
        },
        {
          "type": "category",
          "label": "Gateway Token Endpoints (OAuth2 / JWT)",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "token-service/overview",
            "token-service/token-endpoint",
            "token-service/jwt-endpoint",
            "token-service/introspection",
            "token-service/revocation",
            "token-service/discovery"
          ]
        },
        {
          "type": "category",
          "label": "Appendix",
          "collapsed": true,
          "collapsible": true,
          "items": [
            "appendix",
            "appendix/glossary",
            "appendix/variable-definition",
            "appendix/enum-reference",
            "appendix/openapi-spec"
          ]
        }
      ]
    }
  ]
};

export default sidebars;
