import React, {type ReactNode} from 'react';
import Head from '@docusaurus/Head';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import useBaseUrl from '@docusaurus/useBaseUrl';
import {PageMetadata, useThemeConfig} from '@docusaurus/theme-common';
import {DEFAULT_SEARCH_TAG} from '@docusaurus/theme-common/internal';
import {useLocation} from '@docusaurus/router';
import {applyTrailingSlash} from '@docusaurus/utils-common';
import SearchMetadata from '@theme/SearchMetadata';
import hreflangPairs from '@site/src/data/hreflang-pairs.json';

// Apinizer: TR and EN live in separate docs plugin instances of a single-locale
// site, so Docusaurus' locale-based alternates (hreflang="tr-TR" + x-default on
// every page, both pointing at the page itself) were wrong for EN pages. The
// language is derived from the path instead, and TR⇄EN counterparts come from
// src/data/hreflang-pairs.json (generated by scripts/gen-hreflang-pairs.mjs).
type ContentLang = 'tr' | 'en';

const OG_LOCALE: Record<ContentLang, string> = {tr: 'tr_TR', en: 'en_US'};

const TR_TO_EN = hreflangPairs as Record<string, string>;
const EN_TO_TR: Record<string, string> = Object.fromEntries(
  Object.entries(TR_TO_EN).map(([tr, en]) => [en, tr]),
);

/** /en/**, /api-reference/** → en; /tr/** and site-wide pages (/search, 404) → tr. */
function contentLang(path: string): ContentLang {
  return /^\/(?:en|api-reference)(?:\/|$)/.test(path) ? 'en' : 'tr';
}

function normalizePath(pathname: string): string {
  let path = pathname.replace(/\/+$/, '') || '/';
  try {
    path = decodeURI(path);
  } catch {
    // keep as-is
  }
  return path;
}

function AlternateLangHeaders(): ReactNode {
  const {
    siteConfig: {url: siteUrl},
  } = useDocusaurusContext();
  const {pathname} = useLocation();
  const selfUrl = useDefaultCanonicalUrl();

  const path = normalizePath(pathname);
  const lang = contentLang(path);
  const otherLang: ContentLang = lang === 'en' ? 'tr' : 'en';
  const counterpart = lang === 'en' ? EN_TO_TR[path] : TR_TO_EN[path];
  const counterpartUrl = counterpart ? siteUrl + counterpart : undefined;
  // x-default → the English version when a pair exists, otherwise the page itself.
  const xDefaultUrl = counterpartUrl && lang === 'tr' ? counterpartUrl : selfUrl;

  return (
    <Head>
      <html lang={lang} />
      <link rel="alternate" href={selfUrl} hrefLang={lang} />
      {counterpartUrl && (
        <link rel="alternate" href={counterpartUrl} hrefLang={otherLang} />
      )}
      <link rel="alternate" href={xDefaultUrl} hrefLang="x-default" />
      <meta property="og:locale" content={OG_LOCALE[lang]} />
      {counterpartUrl && (
        <meta property="og:locale:alternate" content={OG_LOCALE[otherLang]} />
      )}
      {/* The search plugin's page emits property="robots", which crawlers ignore. */}
      {path === '/search' && <meta name="robots" content="noindex, follow" />}
    </Head>
  );
}

// Default canonical url inferred from current page location pathname
function useDefaultCanonicalUrl() {
  const {
    siteConfig: {url: siteUrl, baseUrl, trailingSlash},
  } = useDocusaurusContext();

  // TODO using useLocation().pathname is not a super idea
  // See https://github.com/facebook/docusaurus/issues/9170
  const {pathname} = useLocation();

  const canonicalPathname = applyTrailingSlash(useBaseUrl(pathname), {
    trailingSlash,
    baseUrl,
  });

  return siteUrl + canonicalPathname;
}

// TODO move to SiteMetadataDefaults or theme-common ?
function CanonicalUrlHeaders({permalink}: {permalink?: string}) {
  const {
    siteConfig: {url: siteUrl},
  } = useDocusaurusContext();
  const defaultCanonicalUrl = useDefaultCanonicalUrl();

  const canonicalUrl = permalink
    ? `${siteUrl}${permalink}`
    : defaultCanonicalUrl;
  return (
    <Head>
      <meta property="og:url" content={canonicalUrl} />
      <link rel="canonical" href={canonicalUrl} />
    </Head>
  );
}

export default function SiteMetadata(): ReactNode {
  const {
    i18n: {currentLocale},
  } = useDocusaurusContext();

  // TODO maybe move these 2 themeConfig to siteConfig?
  // These seems useful for other themes as well
  const {metadata, image: defaultImage} = useThemeConfig();

  return (
    <>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        {/* The keyboard focus class name need to be applied when SSR so links
        are outlined when JS is disabled */}
        <body />
      </Head>

      {defaultImage && <PageMetadata image={defaultImage} />}

      <CanonicalUrlHeaders />

      <AlternateLangHeaders />

      <SearchMetadata tag={DEFAULT_SEARCH_TAG} locale={currentLocale} />

      {/*
        It's important to have an additional <Head> element here, as it allows
        react-helmet to override default metadata values set in previous <Head>
        like "twitter:card". In same Head, the same meta would appear twice
        instead of overriding.
      */}
      <Head>
        {/* Yes, "metadatum" is the grammatically correct term */}
        {metadata.map((metadatum, i) => (
          <meta key={i} {...metadatum} />
        ))}
      </Head>
    </>
  );
}
